#!/usr/bin/env python3
"""
bootstrap.py
============
Wires the stack together via API after first boot.
Run ONCE after the stack is up. Safe to re-run (idempotent).

On Unraid: pip-installed packages do NOT persist across reboots because
Unraid runs in RAM. This script installs its dependencies inline at the
start of every run so it always works regardless of reboot history.

Usage:
  python3 /mnt/user/appdata/homeserver/homeserver/scripts/bootstrap.py

What it does:
  Radarr   — root folder, SABnzbd download client, hardlinks enabled
  Sonarr   — same
  Lidarr   — same
  Prowlarr — NZBGeek + NZBPlanet indexers, connects all three *arr apps, syncs
  Plex     — creates Movies / TV Shows / Music libraries, triggers scan
"""

import argparse
import getpass
import subprocess
import sys

# ---------------------------------------------------------------------------
# Inline dependency installation
# Unraid does not persist pip packages across reboots.
# We install to /tmp so we don't litter the system.
# ---------------------------------------------------------------------------
def ensure_deps() -> None:
    import importlib
    missing = []
    for pkg, import_name in [("requests", "requests"), ("plexapi", "plexapi")]:
        try:
            importlib.import_module(import_name)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"Installing missing packages: {', '.join(missing)}")
        subprocess.check_call([
            sys.executable, "-m", "pip", "install",
            "--quiet", "--target", "/tmp/bootstrap-deps",
            *missing
        ])
        sys.path.insert(0, "/tmp/bootstrap-deps")
        print("Done.\n")

ensure_deps()

import time
from pathlib import Path
from typing import Optional

import requests

# ---------------------------------------------------------------------------
# Paths and env loading
# Paths are module-level but mutable at argparse time (via --stack-dir)
# before main() dispatches.
# ---------------------------------------------------------------------------
STACK_DIR: Path      = Path(__file__).resolve().parent.parent   # homeserver/
ENV_FILE: Path       = STACK_DIR / ".env"
GENERATED_FILE: Path = STACK_DIR / "generated.env"
DOCKER_ENV: Path     = STACK_DIR / ".env.docker"

def _parse_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                val = val.split("#")[0].strip()
                env[key.strip()] = val
    return env

def load_env() -> dict:
    """Load and merge .env and generated.env. generated.env wins on conflict."""
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found — run generate-configs.py first")
        sys.exit(1)
    env = _parse_env_file(ENV_FILE)
    if GENERATED_FILE.exists():
        env.update(_parse_env_file(GENERATED_FILE))
    return env

def write_generated(updates: dict) -> None:
    """Append or update keys in generated.env."""
    existing = _parse_env_file(GENERATED_FILE) if GENERATED_FILE.exists() else {}
    existing.update(updates)
    lines = ["# Auto-generated by scripts — do not edit by hand\n"]
    for k, v in existing.items():
        lines.append(f"{k}={v}\n")
    GENERATED_FILE.write_text("".join(lines))
    GENERATED_FILE.chmod(0o600)

def refresh_docker_env() -> None:
    """Rewrite .env.docker after generated.env changes."""
    merged = {}
    for path in (ENV_FILE, GENERATED_FILE):
        if path.exists():
            merged.update(_parse_env_file(path))
    lines = ["# Merged env — auto-generated, do not edit\n"]
    for k, v in merged.items():
        lines.append(f"{k}={v}\n")
    DOCKER_ENV.write_text("".join(lines))
    DOCKER_ENV.chmod(0o600)

def require(env: dict, key: str) -> str:
    val = env.get(key, "").strip()
    if not val:
        print(f"ERROR: {key} is not set in .env")
        sys.exit(1)
    return val

def get(env: dict, key: str, default: str = "") -> str:
    return env.get(key, "").strip() or default

# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------
def arr_get(base: str, key: str, path: str) -> dict:
    r = requests.get(f"{base}{path}", headers={"X-Api-Key": key}, timeout=15)
    r.raise_for_status()
    return r.json()

def arr_post(base: str, key: str, path: str, body: dict) -> dict:
    r = requests.post(
        f"{base}{path}", json=body,
        headers={"X-Api-Key": key, "Content-Type": "application/json"},
        timeout=15
    )
    r.raise_for_status()
    return r.json()

def arr_put(base: str, key: str, path: str, body: dict) -> dict:
    r = requests.put(
        f"{base}{path}", json=body,
        headers={"X-Api-Key": key, "Content-Type": "application/json"},
        timeout=15
    )
    r.raise_for_status()
    return r.json()

def already_exists(base: str, key: str, list_path: str, name_field: str, name: str) -> bool:
    try:
        items = arr_get(base, key, list_path)
        return any(str(i.get(name_field, "")).lower() == name.lower() for i in items)
    except Exception:
        return False

def wait_for(url: str, label: str, timeout: int = 180) -> None:
    """Poll until `url` responds with a non-5xx, or bail after `timeout` seconds.

    Exponential backoff with a 15s ceiling. A connection error means the
    service hasn't bound its port yet (still starting — keep waiting).
    A 5xx means the service bound a port but is broken (still transient
    during first-boot DB migrations — keep waiting, but surface the detail).
    """
    print(f"  Waiting for {label}...", end="", flush=True)
    deadline = time.time() + timeout
    delay = 1.0
    last_err = None
    while time.time() < deadline:
        try:
            r = requests.get(url, timeout=5)
            if r.status_code < 500:
                print(" ready")
                return
            last_err = f"HTTP {r.status_code}"
        except requests.ConnectionError:
            last_err = "connection refused"
        except requests.Timeout:
            last_err = "timeout"
        except Exception as e:
            last_err = type(e).__name__
        print(".", end="", flush=True)
        time.sleep(delay)
        delay = min(delay * 1.5, 15.0)
    print(f"\nERROR: {label} did not come up within {timeout}s (last: {last_err})")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configure an *arr app: root folder + SABnzbd client + media management
# ---------------------------------------------------------------------------
def configure_arr(label: str, base: str, key: str, root_folder: str,
                  sabnzbd_category: str, sabnzbd_key: str,
                  extra_mm: Optional[dict] = None) -> None:

    # Each *arr names the SABnzbd category field differently.
    # Source of truth: /api/<ver>/downloadclient/schema → fields[].name where
    # implementation == "Sabnzbd". Passing the wrong name 400s the request.
    category_field = {
        "Radarr": "movieCategory",
        "Sonarr": "tvCategory",
        "Lidarr": "musicCategory",
    }[label]

    # Lidarr 2.x is still on the v1 API; Radarr v5 / Sonarr v4 are on v3.
    # The wait_for() check uses sub-500 = "ready", so a 404 on the wrong
    # version still passes the up-check — but real config calls 404 here.
    api_ver = "v1" if label == "Lidarr" else "v3"

    # Root folder. Lidarr's POST /rootfolder rejects bare {"path": ...} —
    # it requires a name, default quality + metadata profile IDs, and
    # default monitor options (these get applied to artists added under
    # this root folder). Radarr/Sonarr only need {"path": ...}.
    existing_roots = arr_get(base, key, f"/api/{api_ver}/rootfolder")
    if any(f["path"] == root_folder for f in existing_roots):
        print(f"  ✓ {label}: root folder already set")
    else:
        if label == "Lidarr":
            qprofs = arr_get(base, key, f"/api/{api_ver}/qualityprofile")
            mprofs = arr_get(base, key, f"/api/{api_ver}/metadataprofile")
            # Prefer 'Standard' if Lidarr's stock profiles are present;
            # fall back to the first available so a customised install
            # (someone deleted Standard) still works.
            qid = next((p["id"] for p in qprofs if p["name"] == "Standard"),
                       qprofs[0]["id"])
            mid = next((p["id"] for p in mprofs if p["name"] == "Standard"),
                       mprofs[0]["id"])
            payload = {
                "name": "Music",
                "path": root_folder,
                "defaultQualityProfileId": qid,
                "defaultMetadataProfileId": mid,
                "defaultMonitorOption": "all",
                "defaultNewItemMonitorOption": "all",
                "defaultTags": [],
            }
        else:
            payload = {"path": root_folder}
        arr_post(base, key, f"/api/{api_ver}/rootfolder", payload)
        print(f"  ✓ {label}: root folder → {root_folder}")

    # SABnzbd download client
    if already_exists(base, key, f"/api/{api_ver}/downloadclient", "name", "SABnzbd"):
        print(f"  ✓ {label}: SABnzbd already connected")
    else:
        arr_post(base, key, f"/api/{api_ver}/downloadclient", {
            "enable": True,
            "protocol": "usenet",
            "priority": 1,
            "name": "SABnzbd",
            "fields": [
                # SAB shares gluetun's netns and has no bridge endpoint of
                # its own, so from any other container's POV its UI lives at
                # gluetun:8080. Resolving "sabnzbd" via docker DNS fails.
                {"name": "host",           "value": "gluetun"},
                {"name": "port",           "value": 8080},
                {"name": "apiKey",         "value": sabnzbd_key},
                {"name": "urlBase",        "value": "/sabnzbd"},
                {"name": category_field,   "value": sabnzbd_category},
                {"name": "useSsl",         "value": False},
            ],
            "implementationName": "SABnzbd",
            "implementation": "Sabnzbd",
            "configContract": "SabnzbdSettings",
            "tags": []
        })
        print(f"  ✓ {label}: SABnzbd download client added (category: {sabnzbd_category})")

    # Media management: enable hardlinks, import extra files
    try:
        current = arr_get(base, key, f"/api/{api_ver}/config/mediamanagement")
        updated = {**current,
                   "copyUsingHardlinks": True,
                   "deleteEmptyFolders": True,
                   "importExtraFiles": True,
                   **(extra_mm or {})}
        arr_put(base, key, f"/api/{api_ver}/config/mediamanagement", updated)
        print(f"  ✓ {label}: hardlinks enabled")
    except Exception as e:
        print(f"  ⚠ {label}: media management update failed: {e}")

# ---------------------------------------------------------------------------
# Configure Prowlarr: add indexers, connect arr apps, sync
# ---------------------------------------------------------------------------
def configure_prowlarr(base: str, key: str, env: dict) -> None:

    def add_indexer(name: str, schema_name: str, api_key_value: str) -> None:
        if already_exists(base, key, "/api/v1/indexer", "name", name):
            print(f"  ✓ Prowlarr: {name} already added")
            return
        try:
            schemas = arr_get(base, key, "/api/v1/indexer/schema")
        except Exception as e:
            print(f"  ⚠ Prowlarr: could not fetch schemas: {e}")
            return
        # Match on schema 'name' (e.g. "NZBgeek", "NzbPlanet") — not on
        # 'definitionName', which is the protocol family ("Newznab",
        # "Torznab"). Every Newznab-based indexer shares the same
        # definitionName, so matching that can't disambiguate. Compare
        # case-insensitively to tolerate upstream casing shifts (NZBgeek
        # vs NZBGeek, etc.).
        schema = next(
            (s for s in schemas if (s.get("name") or "").lower() == schema_name.lower()),
            None
        )
        if not schema:
            print(f"  ⚠ Prowlarr: schema not found for '{schema_name}' — check indexer name")
            return
        for field in schema.get("fields", []):
            if field.get("name") == "apiKey":
                field["value"] = api_key_value
        schema["name"] = name
        schema["enable"] = True
        schema["appProfileId"] = 1
        try:
            arr_post(base, key, "/api/v1/indexer", schema)
            print(f"  ✓ Prowlarr: {name} added")
        except Exception as e:
            print(f"  ⚠ Prowlarr: failed to add {name}: {e}")

    def add_app(name: str, app_url: str, app_key: str, impl: str, contract: str) -> None:
        if already_exists(base, key, "/api/v1/applications", "name", name):
            print(f"  ✓ Prowlarr: {name} already connected")
            return
        try:
            arr_post(base, key, "/api/v1/applications", {
                "name": name,
                "syncLevel": "fullSync",
                "fields": [
                    # Prowlarr shares gluetun's netns; from each *arr's POV
                    # its API is reachable at gluetun:9696, not prowlarr:9696.
                    {"name": "prowlarrUrl", "value": "http://gluetun:9696/prowlarr"},
                    {"name": "baseUrl",     "value": app_url},
                    {"name": "apiKey",      "value": app_key},
                    {"name": "syncCategories",
                     "value": [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060]},
                ],
                "implementationName": name,
                "implementation": impl,
                "configContract": contract,
                "tags": []
            })
            print(f"  ✓ Prowlarr: {name} connected")
        except Exception as e:
            print(f"  ⚠ Prowlarr: failed to connect {name}: {e}")

    add_indexer("NZBGeek",   "nzbgeek",   require(env, "NZBGEEK_API_KEY"))
    add_indexer("NZBPlanet", "nzbplanet", require(env, "NZBPLANET_API_KEY"))

    add_app("Radarr", "http://radarr:7878/radarr",
            require(env, "RADARR_API_KEY"),   "Radarr", "RadarrSettings")
    add_app("Sonarr", "http://sonarr:8989/sonarr",
            require(env, "SONARR_API_KEY"),   "Sonarr", "SonarrSettings")
    add_app("Lidarr", "http://lidarr:8686/lidarr",
            require(env, "LIDARR_API_KEY"),   "Lidarr", "LidarrSettings")

    # Trigger sync
    try:
        requests.post(f"{base}/api/v1/applications/sync",
                      headers={"X-Api-Key": key}, timeout=15)
        print("  ✓ Prowlarr: indexer sync triggered")
    except Exception as e:
        print(f"  ⚠ Prowlarr: sync trigger failed: {e}")

# ---------------------------------------------------------------------------
# Configure Plex: create libraries, trigger scan
# ---------------------------------------------------------------------------
def configure_plex(token: str, lan_ip: str):
    """Create libraries + trigger scan. Returns the connected PlexServer so
    downstream steps (Tautulli pre-seed) can reuse it, or None on failure."""
    try:
        from plexapi.server import PlexServer
        from plexapi.exceptions import BadRequest
    except ImportError:
        print("  ⚠ Plex: plexapi import failed after install — try re-running")
        return None

    try:
        plex = PlexServer(f"http://{lan_ip}:32400", token)
    except Exception as e:
        print(f"  ⚠ Plex: could not connect: {e}")
        print("    Check PLEX_LAN_IP and PLEX_TOKEN in .env")
        return None

    existing = {s.title for s in plex.library.sections()}

    for name, ltype, path, agent, scanner in [
        ("Movies",   "movie",  "/data/media/movies", "tv.plex.agents.movie",  "Plex Movie"),
        ("TV Shows", "show",   "/data/media/tv",      "tv.plex.agents.series", "Plex TV Series"),
        ("Music",    "artist", "/data/media/music",   "tv.plex.agents.music",  "Plex Music"),
    ]:
        if name in existing:
            print(f"  ✓ Plex: '{name}' already exists")
            continue
        try:
            # The new tv.plex.agents.* agents require BCP-47 locale tags
            # (en-US, en-GB, …); the legacy two-letter form ("en") returns
            # 400 'language' is invalid.
            plex.library.add(name=name, type=ltype, agent=agent,
                             scanner=scanner, location=path, language="en-US")
            print(f"  ✓ Plex: created library '{name}'")
        except BadRequest as e:
            print(f"  ⚠ Plex: could not create '{name}': {e}")

    for section in plex.library.sections():
        section.update()
    print("  ✓ Plex: library scan triggered")
    return plex

# ---------------------------------------------------------------------------
# Configure Tautulli: skip its first-run wizard by pre-seeding PMS fields
# ---------------------------------------------------------------------------
def configure_tautulli(plex, token: str) -> None:
    """Pre-seed Tautulli's PMS connection so the first-run wizard is skipped.

    config.ini is bind-mounted from ${STACK_DIR}/configs/tautulli/config.ini
    to /config/config.ini inside the container (see docker-compose.yml).
    Rewriting the host file in-place preserves the inode so the bind mount
    stays pointed at the right content. A docker restart picks it up.

    `plex` is a connected plexapi.PlexServer; we pull machineIdentifier and
    friendlyName straight off it. `token` is passed explicitly because
    plexapi stores it as a private attribute and we'd rather not rely on
    that stability.
    """
    import configparser

    config_path = STACK_DIR / "configs" / "tautulli" / "config.ini"
    if not config_path.exists():
        print(f"  ⚠ Tautulli: {config_path} missing — run generate-configs.py first")
        return

    cfg = configparser.ConfigParser()
    cfg.read(config_path)

    if cfg.has_option("General", "first_run_complete") and \
       cfg.get("General", "first_run_complete") == "1":
        print("  ✓ Tautulli: first-run already complete")
        return

    if not cfg.has_section("General"):
        cfg.add_section("General")
    if not cfg.has_section("PMS"):
        cfg.add_section("PMS")

    cfg.set("General", "first_run_complete", "1")
    # Tautulli talks to Plex over the frontend docker network — container DNS
    # name "plex" resolves to the PMS container's IP on that bridge.
    cfg.set("PMS", "pms_ip",         "plex")
    cfg.set("PMS", "pms_port",       "32400")
    cfg.set("PMS", "pms_ssl",        "0")
    cfg.set("PMS", "pms_is_cloud",   "0")
    cfg.set("PMS", "pms_is_remote",  "0")
    cfg.set("PMS", "pms_url_manual", "0")
    cfg.set("PMS", "pms_identifier", plex.machineIdentifier)
    cfg.set("PMS", "pms_name",       plex.friendlyName)
    cfg.set("PMS", "pms_token",      token)

    # Truncate-in-place so the bind-mounted inode survives.
    with open(config_path, "w") as f:
        cfg.write(f)
    config_path.chmod(0o600)
    print(f"  ✓ Tautulli: seeded PMS connection → {plex.friendlyName}")

    try:
        subprocess.run(
            ["docker", "restart", "tautulli"],
            check=True, capture_output=True, text=True,
        )
        print("  ✓ Tautulli: restarted to pick up new config")
    except subprocess.CalledProcessError as e:
        print(f"  ⚠ Tautulli: restart failed: {e.stderr.strip()[:200]}")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Wire the homeserver stack together via API after first boot."
    )
    p.add_argument(
        "--stack-dir", type=Path,
        help="Override the homeserver/ directory (default: inferred from script location)"
    )
    p.add_argument(
        "--timeout", type=int, default=180,
        help="Per-service wait timeout in seconds (default: 180)"
    )
    return p.parse_args()


def main() -> None:
    global STACK_DIR, ENV_FILE, GENERATED_FILE, DOCKER_ENV
    args = _parse_args()
    if args.stack_dir:
        STACK_DIR = args.stack_dir.resolve()
        ENV_FILE = STACK_DIR / ".env"
        GENERATED_FILE = STACK_DIR / "generated.env"
        DOCKER_ENV = STACK_DIR / ".env.docker"

    env = load_env()
    lan_ip = require(env, "PLEX_LAN_IP")
    sabnzbd_key = require(env, "SABNZBD_API_KEY")

    SERVICES = {
        "radarr":   (f"http://localhost:7878/radarr",   require(env, "RADARR_API_KEY")),
        "sonarr":   (f"http://localhost:8989/sonarr",   require(env, "SONARR_API_KEY")),
        "lidarr":   (f"http://localhost:8686/lidarr",   require(env, "LIDARR_API_KEY")),
        "prowlarr": (f"http://localhost:9696/prowlarr", require(env, "PROWLARR_API_KEY")),
    }

    print("\n=== Waiting for services ===\n")
    wait_for("http://localhost:8080/sabnzbd/api?mode=version", "sabnzbd",
             timeout=args.timeout)
    for name, (url, _key) in SERVICES.items():
        api_ver = "v1" if name == "prowlarr" else "v3"
        wait_for(f"{url}/api/{api_ver}/system/status", name, timeout=args.timeout)
    wait_for("http://localhost:5055", "seerr", timeout=args.timeout)

    print("\n=== Radarr ===\n")
    url, key = SERVICES["radarr"]
    configure_arr("Radarr", url, key, "/data/media/movies", "movies", sabnzbd_key)

    print("\n=== Sonarr ===\n")
    url, key = SERVICES["sonarr"]
    configure_arr("Sonarr", url, key, "/data/media/tv", "tv", sabnzbd_key,
                  extra_mm={"createEmptySeriesFolders": False})

    print("\n=== Lidarr ===\n")
    url, key = SERVICES["lidarr"]
    configure_arr("Lidarr", url, key, "/data/media/music", "music", sabnzbd_key)

    print("\n=== Prowlarr ===\n")
    url, key = SERVICES["prowlarr"]
    configure_prowlarr(url, key, env)

    print("\n=== Plex ===\n")
    plex_token = get(env, "PLEX_TOKEN")
    if not plex_token:
        print("  Plex token not found in .env.")
        print(f"  1. Open http://{lan_ip}:32400/web in your browser")
        print("  2. Sign in with your Plex account")
        print("  3. Settings → General → scroll to bottom → click 'Show'")
        print("  4. Copy the X-Plex-Token value\n")
        # getpass suppresses terminal echo and keeps the token out of shell history.
        plex_token = getpass.getpass("  Paste PLEX_TOKEN here (or press Enter to skip): ").strip()
        if plex_token:
            write_generated({"PLEX_TOKEN": plex_token})
            refresh_docker_env()
            print("  ✓ PLEX_TOKEN saved to generated.env\n")

    plex = None
    if plex_token:
        plex = configure_plex(plex_token, lan_ip)
        # PLEX_CLAIM tokens are single-use and expire after ~4 minutes.
        # Once we've got a PLEX_TOKEN the claim is spent — blank it so a later
        # redeploy doesn't feed a dead claim into a freshly-recreated Plex.
        if get(env, "PLEX_CLAIM"):
            write_generated({"PLEX_CLAIM": ""})
            refresh_docker_env()
            print("  ✓ PLEX_CLAIM cleared (one-time-use, already consumed)")
    else:
        print("  ⚠ Skipped — re-run this script after signing into Plex")

    print("\n=== Tautulli ===\n")
    if plex is not None:
        configure_tautulli(plex, plex_token)
    else:
        print("  ⚠ Skipped — needs a working Plex connection from the previous step")

    print("\n=== Done ===\n")
    print("Stack is fully configured. Access points:")
    print(f"  SABnzbd:   http://{lan_ip}:8080/sabnzbd")
    print(f"  Prowlarr:  http://{lan_ip}:9696/prowlarr")
    print(f"  Radarr:    http://{lan_ip}:7878/radarr")
    print(f"  Sonarr:    http://{lan_ip}:8989/sonarr")
    print(f"  Lidarr:    http://{lan_ip}:8686/lidarr")
    print(f"  Plex:      http://{lan_ip}:32400/web")
    print(f"  Seerr:     http://{lan_ip}:5055")
    print()
    print("Admin UIs (everything above except Plex) are reachable via")
    print("Tailscale MagicDNS from any device on your tailnet.")
    print()
    print("Remaining manual steps:")
    print("  1. Plex → Settings → Transcoder → Use hardware acceleration when")
    print("     available → select NVIDIA GeForce RTX 3050 (requires Plex Pass —")
    print("     cannot be set via API).")
    print("  2. Seerr → sign in with your Plex account, then Settings → Users →")
    print("     edit each family member → grant 'Auto-Request' so their Plex")
    print("     Watchlist additions become Radarr/Sonarr requests automatically.")
    print("     (Per-user grant; Seerr ties it to each Plex SSO identity.)")
    print(f"  3. Profilarr → http://{lan_ip}:6868 → add Radarr + Sonarr as sync")
    print("     targets (paste URLs + API keys from generated.env), subscribe to")
    print("     the Dictionarry DB and/or TRaSH Guides, select profiles, sync.")
    print("     Profilarr has no API-driven bootstrap path.")

if __name__ == "__main__":
    main()
