#!/usr/bin/env python3
"""
bootstrap.py
============
Wires the stack together via API after first boot.
Run ONCE after the stack is up. Safe to re-run (idempotent).

On Unraid: pip-installed packages do NOT persist across reboots because
Unraid runs in RAM. This script installs its dependencies inline at the
start of every run so it always works regardless of reboot history.

Usage:
  python3 /mnt/user/appdata/homeserver/homeserver/scripts/bootstrap.py

What it does:
  Radarr   — root folder, SABnzbd download client, hardlinks enabled
  Sonarr   — same
  Prowlarr — NZBGeek + NZBPlanet indexers, connects both *arr apps, syncs
  Plex     — creates Movies / TV Shows / Music libraries, triggers scan
"""

import argparse
import getpass
import re
import subprocess
import sys

# ---------------------------------------------------------------------------
# Inline dependency installation
# Unraid does not persist pip packages across reboots.
# We install to /tmp so we don't litter the system.
# ---------------------------------------------------------------------------
def ensure_deps() -> None:
    import importlib
    missing = []
    for pkg, import_name in [("requests", "requests"), ("plexapi", "plexapi")]:
        try:
            importlib.import_module(import_name)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"Installing missing packages: {', '.join(missing)}")
        subprocess.check_call([
            sys.executable, "-m", "pip", "install",
            "--quiet", "--target", "/tmp/bootstrap-deps",
            *missing
        ])
        sys.path.insert(0, "/tmp/bootstrap-deps")
        print("Done.\n")

ensure_deps()

import time
from pathlib import Path
from typing import Optional

import requests

# ---------------------------------------------------------------------------
# Paths and env loading
# Paths are module-level but mutable at argparse time (via --stack-dir)
# before main() dispatches.
# ---------------------------------------------------------------------------
STACK_DIR: Path      = Path(__file__).resolve().parent.parent   # homeserver/
ENV_FILE: Path       = STACK_DIR / ".env"
GENERATED_FILE: Path = STACK_DIR / "generated.env"
DOCKER_ENV: Path     = STACK_DIR / ".env.docker"

def _parse_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                # A `#` only starts a comment when it FOLLOWS WHITESPACE —
                # matching dotenv convention, where `KEY=#foo` is the literal
                # value `#foo`. `val.split("#")[0]` treated every `#` as a
                # comment, which silently truncated any password containing one
                # — `p@ss#word1` became `p@ss`. That failure hid well: the
                # freshly-typed value is still in memory on the first run, so
                # sabnzbd.ini was written correctly and everything worked. Only
                # a LATER run re-read `.env`, got the truncated value, and left
                # the provider rejecting the login with nothing in any log
                # pointing at the password.
                val = re.split(r"\s#", val, maxsplit=1)[0].strip()
                env[key.strip()] = val
    return env

def load_env() -> dict:
    """Load and merge .env and generated.env. generated.env wins on conflict."""
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found — run generate-configs.py first")
        sys.exit(1)
    env = _parse_env_file(ENV_FILE)
    if GENERATED_FILE.exists():
        env.update(_parse_env_file(GENERATED_FILE))
    return env

def write_generated(updates: dict) -> None:
    """Append or update keys in generated.env."""
    existing = _parse_env_file(GENERATED_FILE) if GENERATED_FILE.exists() else {}
    existing.update(updates)
    lines = ["# Auto-generated by scripts — do not edit by hand\n"]
    for k, v in existing.items():
        lines.append(f"{k}={v}\n")
    GENERATED_FILE.write_text("".join(lines))
    GENERATED_FILE.chmod(0o600)

def refresh_docker_env() -> None:
    """Rewrite .env.docker after generated.env changes."""
    merged = {}
    for path in (ENV_FILE, GENERATED_FILE):
        if path.exists():
            merged.update(_parse_env_file(path))
    lines = ["# Merged env — auto-generated, do not edit\n"]
    for k, v in merged.items():
        lines.append(f"{k}={v}\n")
    DOCKER_ENV.write_text("".join(lines))
    DOCKER_ENV.chmod(0o600)

def require(env: dict, key: str) -> str:
    val = env.get(key, "").strip()
    if not val:
        print(f"ERROR: {key} is not set in .env")
        sys.exit(1)
    return val

def get(env: dict, key: str, default: str = "") -> str:
    return env.get(key, "").strip() or default

# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------
def arr_get(base: str, key: str, path: str) -> dict:
    r = requests.get(f"{base}{path}", headers={"X-Api-Key": key}, timeout=15)
    r.raise_for_status()
    return r.json()

def arr_post(base: str, key: str, path: str, body: dict) -> dict:
    r = requests.post(
        f"{base}{path}", json=body,
        headers={"X-Api-Key": key, "Content-Type": "application/json"},
        timeout=15
    )
    r.raise_for_status()
    return r.json()

def arr_put(base: str, key: str, path: str, body: dict) -> dict:
    r = requests.put(
        f"{base}{path}", json=body,
        headers={"X-Api-Key": key, "Content-Type": "application/json"},
        timeout=15
    )
    r.raise_for_status()
    return r.json()

def already_exists(base: str, key: str, list_path: str, name_field: str, name: str) -> bool:
    try:
        items = arr_get(base, key, list_path)
        return any(str(i.get(name_field, "")).lower() == name.lower() for i in items)
    except Exception:
        return False

def reconcile_fields(existing: dict, *, top_level: Optional[dict] = None,
                     fields: Optional[dict] = None) -> bool:
    """Patch `existing` in place to match desired values; return True if anything
    changed.

    Used to bring previously-bootstrapped *arr download clients and Prowlarr
    application connections in line with current desired state without
    deleting and recreating them (which would lose user-side history). Both
    *arrs and Prowlarr expose configuration objects with two layers — top-
    level flags (`removeCompletedDownloads`, `enable`, …) and a `fields`
    array of `{name, value}` dicts. We diff each layer separately.
    """
    changed = False
    for k, v in (top_level or {}).items():
        if existing.get(k) != v:
            existing[k] = v
            changed = True
    if fields:
        for f in existing.get("fields", []):
            name = f.get("name")
            if name in fields and f.get("value") != fields[name]:
                f["value"] = fields[name]
                changed = True
    return changed

def wait_for(url: str, label: str, timeout: int = 180) -> None:
    """Poll until `url` responds with a non-5xx, or bail after `timeout` seconds.

    Exponential backoff with a 15s ceiling. A connection error means the
    service hasn't bound its port yet (still starting — keep waiting).
    A 5xx means the service bound a port but is broken (still transient
    during first-boot DB migrations — keep waiting, but surface the detail).
    """
    print(f"  Waiting for {label}...", end="", flush=True)
    deadline = time.time() + timeout
    delay = 1.0
    last_err = None
    while time.time() < deadline:
        try:
            r = requests.get(url, timeout=5)
            if r.status_code < 500:
                print(" ready")
                return
            last_err = f"HTTP {r.status_code}"
        except requests.ConnectionError:
            last_err = "connection refused"
        except requests.Timeout:
            last_err = "timeout"
        except Exception as e:
            last_err = type(e).__name__
        print(".", end="", flush=True)
        time.sleep(delay)
        delay = min(delay * 1.5, 15.0)
    print(f"\nERROR: {label} did not come up within {timeout}s (last: {last_err})")
    sys.exit(1)

def await_command(base: str, key: str, cmd_id: Optional[int], label: str,
                  timeout: int = 90) -> None:
    """Poll a queued *arr command to completion and report its real outcome.

    Worth the extra round-trips. A command is accepted asynchronously, so a
    202 proves only that it was queued — a sync that starts and then fails
    reports nothing to the caller. The bug this exists to prevent was exactly
    that shape: a sync announced as done that had in fact never run.
    """
    if not cmd_id:
        return
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            status = arr_get(base, key, f"/api/v1/command/{cmd_id}").get("status")
        except Exception as e:
            print(f"  ⚠ {label}: could not read command status: {e}")
            return
        if status == "completed":
            print(f"  ✓ {label}: completed")
            return
        if status in ("failed", "aborted", "cancelled"):
            print(f"  ⚠ {label}: {status} — Prowlarr → System → Tasks for why")
            return
        time.sleep(2)
    print(f"  ⚠ {label}: still running after {timeout}s — check Prowlarr → System → Tasks")

# ---------------------------------------------------------------------------
# Configure an *arr app: root folder + SABnzbd client + media management
# ---------------------------------------------------------------------------
def configure_arr(label: str, base: str, key: str, root_folder: str,
                  sabnzbd_category: str, sabnzbd_key: str,
                  extra_mm: Optional[dict] = None) -> None:

    # Each *arr names the SABnzbd category field differently.
    # Source of truth: /api/<ver>/downloadclient/schema → fields[].name where
    # implementation == "Sabnzbd". Passing the wrong name 400s the request.
    category_field = {
        "Radarr": "movieCategory",
        "Sonarr": "tvCategory",
    }[label]

    # Radarr v5 / Sonarr v4 are both on the v3 API.
    api_ver = "v3"

    # Root folder. Radarr/Sonarr only need {"path": ...}.
    existing_roots = arr_get(base, key, f"/api/{api_ver}/rootfolder")
    if any(f["path"] == root_folder for f in existing_roots):
        print(f"  ✓ {label}: root folder already set")
    else:
        payload = {"path": root_folder}
        arr_post(base, key, f"/api/{api_ver}/rootfolder", payload)
        print(f"  ✓ {label}: root folder → {root_folder}")

    # SABnzbd download client. Desired state captured in desired_top +
    # desired_fields so:
    #   - new installs: full payload constructed from these dicts
    #   - existing installs: reconcile_fields() drives any field that has
    #     drifted from desired (host, port, urlBase, etc.) without losing
    #     unrelated *arr-side state.
    #
    # removeCompletedDownloads=True: after a successful import the *arr tells
    # SAB to remove the job, which is what actually deletes the files under
    # usenet/complete. The *arr is the only component that CAN do this — it
    # is the one that knows the import succeeded and where the file went.
    #
    # This was False, justified by "SAB's history_retention handles cleanup
    # independently". That is wrong. SABnzbd's history retention moves or
    # deletes HISTORY ENTRIES only; upstream is explicit that delete-files was
    # never supported for successfully completed jobs, because sorting rules
    # and user scripts make the final location unknowable to SAB. With this
    # False and nothing else cleaning up, complete/ reached 324 GB across 127
    # job folders on the live box — including _UNPACK_ failures, a _FAILED_
    # job, and five copies of the same episode from repeated re-grabs.
    #
    # The removal fires only after a successful import, so it does not race
    # post-processing. The separate *arr health warning about removing
    # completed downloads concerns the DOWNLOAD CLIENT auto-deleting on its
    # own schedule, which is a different setting and still off.
    #
    # host=gluetun because SAB shares gluetun's netns; from any other
    # container's POV the SAB UI lives at gluetun:8080. Docker DNS for
    # "sabnzbd" doesn't resolve.
    desired_top = {"removeCompletedDownloads": True}
    desired_fields = {
        "host":         "gluetun",
        "port":         8080,
        "apiKey":       sabnzbd_key,
        "urlBase":      "",
        category_field: sabnzbd_category,
        "useSsl":       False,
    }
    existing_clients = arr_get(base, key, f"/api/{api_ver}/downloadclient")
    sab_client = next((c for c in existing_clients if c.get("name") == "SABnzbd"), None)
    if sab_client is not None:
        if reconcile_fields(sab_client, top_level=desired_top, fields=desired_fields):
            arr_put(base, key, f"/api/{api_ver}/downloadclient/{sab_client['id']}", sab_client)
            print(f"  ✓ {label}: SABnzbd reconciled")
        else:
            print(f"  ✓ {label}: SABnzbd already connected")
    else:
        arr_post(base, key, f"/api/{api_ver}/downloadclient", {
            "enable": True,
            "protocol": "usenet",
            "priority": 1,
            "name": "SABnzbd",
            **desired_top,
            "fields": [{"name": k, "value": v} for k, v in desired_fields.items()],
            "implementationName": "SABnzbd",
            "implementation": "Sabnzbd",
            "configContract": "SabnzbdSettings",
            "tags": []
        })
        print(f"  ✓ {label}: SABnzbd download client added (category: {sabnzbd_category})")

    # Media management: enable hardlinks, import extra files
    try:
        current = arr_get(base, key, f"/api/{api_ver}/config/mediamanagement")
        updated = {**current,
                   "copyUsingHardlinks": True,
                   "deleteEmptyFolders": True,
                   "importExtraFiles": True,
                   **(extra_mm or {})}
        arr_put(base, key, f"/api/{api_ver}/config/mediamanagement", updated)
        print(f"  ✓ {label}: hardlinks enabled")
    except Exception as e:
        print(f"  ⚠ {label}: media management update failed: {e}")

# ---------------------------------------------------------------------------
# Configure Prowlarr: add indexers, connect arr apps, sync
# ---------------------------------------------------------------------------
def configure_prowlarr(base: str, key: str, env: dict) -> None:

    def add_indexer(name: str, schema_name: str, api_key_value: str) -> None:
        if already_exists(base, key, "/api/v1/indexer", "name", name):
            print(f"  ✓ Prowlarr: {name} already added")
            return
        try:
            schemas = arr_get(base, key, "/api/v1/indexer/schema")
        except Exception as e:
            print(f"  ⚠ Prowlarr: could not fetch schemas: {e}")
            return
        # Match on schema 'name' (e.g. "NZBgeek", "NzbPlanet") — not on
        # 'definitionName', which is the protocol family ("Newznab",
        # "Torznab"). Every Newznab-based indexer shares the same
        # definitionName, so matching that can't disambiguate. Compare
        # case-insensitively to tolerate upstream casing shifts (NZBgeek
        # vs NZBGeek, etc.).
        schema = next(
            (s for s in schemas if (s.get("name") or "").lower() == schema_name.lower()),
            None
        )
        if not schema:
            print(f"  ⚠ Prowlarr: schema not found for '{schema_name}' — check indexer name")
            return
        for field in schema.get("fields", []):
            if field.get("name") == "apiKey":
                field["value"] = api_key_value
        schema["name"] = name
        schema["enable"] = True
        schema["appProfileId"] = 1
        try:
            arr_post(base, key, "/api/v1/indexer", schema)
            print(f"  ✓ Prowlarr: {name} added")
        except Exception as e:
            print(f"  ⚠ Prowlarr: failed to add {name}: {e}")

    # Newznab category IDs: 2000s = Movies, 5000s = TV.
    sync_categories = {
        "Radarr": [2000, 2010, 2020, 2030, 2040, 2045, 2050, 2060],
        "Sonarr": [5000, 5010, 5020, 5030, 5040, 5045, 5050, 5060, 5070, 5080],
    }

    def add_app(name: str, app_url: str, app_key: str, impl: str, contract: str) -> None:
        # TWO CLASSES OF FIELD HERE, and the split is the whole point.
        #
        # INFRASTRUCTURE — where things live. These track docker-compose.yml, so
        # the script owns them and reconciles them on every run; a container
        # rename or an ingress change has to propagate or the link breaks.
        # Both Prowlarr and the *arrs serve at root now (UrlBase stripped), so
        # the URLs carry no urlbase suffix, and prowlarrUrl points back through
        # gluetun's netns alias because Prowlarr has no bridge endpoint of its
        # own.
        #
        # POLICY — syncCategories: which categories Prowlarr pushes to this app.
        # That is a USER choice made in Prowlarr's UI, and this script has no
        # business overwriting it. Set once when the connection is created,
        # never touched again.
        #
        # It used to be reconciled alongside the infrastructure fields, and that
        # is precisely how this stack spent months clobbering the Sonarr indexer
        # settings on every bootstrap run: reconcile_fields forced the list back
        # to ours, the PUT raised ProviderUpdatedEvent, Prowlarr re-synced, and
        # Sonarr.cs:272 set each synced indexer's `categories` field to
        # SupportedCategories(app.SyncCategories) — the INTERSECTION of our list
        # with that indexer's advertised caps, top-level and subcategories alike
        # (IndexerCapabilitiesCategories.cs:131). So a category this map names
        # but the indexer does not advertise silently does nothing, and one the
        # user selected but this map omits is silently dropped. Neither is the
        # script's call to make, which is why the field is create-only.
        infra_fields = {
            "prowlarrUrl": "http://gluetun:9696",
            "baseUrl":     app_url,
            "apiKey":      app_key,
        }
        existing_apps = arr_get(base, key, "/api/v1/applications")
        existing = next((a for a in existing_apps if a.get("name") == name), None)
        if existing is not None:
            if reconcile_fields(existing, fields=infra_fields):
                try:
                    arr_put(base, key, f"/api/v1/applications/{existing['id']}", existing)
                    print(f"  ✓ Prowlarr: {name} reconciled")
                except Exception as e:
                    print(f"  ⚠ Prowlarr: failed to reconcile {name}: {e}")
            else:
                print(f"  ✓ Prowlarr: {name} already connected")
            # A disabled sync is a deliberate choice, and it is left alone.
            # Prowlarr excludes disabled apps from SyncEnabled(), so it will
            # never populate this *arr's indexers — they are hand-managed, which
            # is supported, not broken. Say so here so the indexer report at the
            # end of the run is not misread as a fault.
            if existing.get("syncLevel") == "disabled":
                print(f"  · Prowlarr: {name} sync is DISABLED — its indexers are "
                      "hand-managed; Prowlarr will not add or remove any")
            return
        try:
            arr_post(base, key, "/api/v1/applications", {
                "name": name,
                "syncLevel": "fullSync",
                "fields": [{"name": k, "value": v} for k, v in
                           {**infra_fields,
                            "syncCategories": sync_categories[name]}.items()],
                "implementationName": name,
                "implementation": impl,
                "configContract": contract,
                "tags": []
            })
            print(f"  ✓ Prowlarr: {name} connected")
        except Exception as e:
            print(f"  ⚠ Prowlarr: failed to connect {name}: {e}")

    add_indexer("NZBGeek",   "nzbgeek",   require(env, "NZBGEEK_API_KEY"))
    add_indexer("NZBPlanet", "nzbplanet", require(env, "NZBPLANET_API_KEY"))

    add_app("Radarr", "http://radarr:7878",
            require(env, "RADARR_API_KEY"),   "Radarr", "RadarrSettings")
    add_app("Sonarr", "http://sonarr:8989",
            require(env, "SONARR_API_KEY"),   "Sonarr", "SonarrSettings")

    # Force a re-push of every indexer definition into every connected app.
    #
    # This used to POST /api/v1/applications/sync. That is not a Prowlarr
    # endpoint and never has been — the application provider controller
    # exposes only CRUD plus schema/test/testall/action/{name} (checked
    # against Prowlarr's own openapi.json; there is no path anywhere in the
    # v1 API containing "sync"). The call 404'd on every run since it was
    # written. It used a bare requests.post rather than arr_post, so nothing
    # raised, nothing checked r.status_code, and the script printed
    # "✓ indexer sync triggered" every time. The one piece of reconciliation
    # bootstrap.py does not perform itself — the indexer definitions Prowlarr
    # pushes into Radarr/Sonarr — has therefore never actually run.
    #
    # forceSync is the part that matters, not merely the fact of a sync.
    # arr_put on an application above already raises ProviderUpdatedEvent,
    # which syncs on its own; but an unforced sync skips any indexer Prowlarr
    # believes is unchanged, and from Prowlarr's side nothing about the
    # indexer HAS changed when what moved is prowlarrUrl or syncCategories.
    # Only the forced path re-issues UpdateIndexer(definition, force) and
    # rewrites the definition the *arr holds — which is what corrects a
    # baseUrl that has gone stale relative to the values reconciled above.
    #
    # THIS COMMAND ALSO DELETES. ApplicationService.cs:125 calls
    # SyncIndexers(enabledApps, indexers, true, ForceSync) against the signature
    # (applications, indexers, removeRemote = false, forceSync = false) — so
    # removeRemote is TRUE here. Prowlarr adopts indexers it finds in the *arr
    # that were "setup manually in the app" into its mapping table, then removes
    # any whose mapped Prowlarr indexer no longer exists. Hand-added indexers in
    # a sync-ENABLED *arr are therefore fair game for deletion. Apps whose sync
    # is disabled are excluded by SyncEnabled() and never touched, which is what
    # makes disabling the sync a safe way to hand-manage one *arr's indexers.
    try:
        cmd = arr_post(base, key, "/api/v1/command",
                       {"name": "ApplicationIndexerSync", "forceSync": True})
        print("  ✓ Prowlarr: forced indexer sync queued")
        await_command(base, key, cmd.get("id"), "Prowlarr: indexer sync")
    except Exception as e:
        print(f"  ⚠ Prowlarr: sync command failed: {e}")

# ---------------------------------------------------------------------------
# Verify what Prowlarr actually pushed into the *arrs
# ---------------------------------------------------------------------------
def check_synced_indexers(services: dict) -> None:
    """Report *arr indexers whose baseUrl cannot be a working Prowlarr URL.

    Prowlarr writes each synced indexer into the *arr as
    `{prowlarrUrl}/{prowlarr indexer id}/` with apiPath `/api`, so the *arr
    fetches `http://gluetun:9696/<id>/api?t=caps`. Two things routinely leave
    that path wrong, and both fail identically and unhelpfully — the *arr
    reports, on Test and on every search:

        Unable to connect to indexer: 'doctype' is an unexpected token.
        The expected token is 'DOCTYPE'. Line 1, position 3.

    which is .NET's XML parser being handed an HTML page. The request missed
    Prowlarr's `/{id}/api` newznab route and fell through to Prowlarr's SPA,
    so what came back was a web page where Newznab XML was expected. Note it
    is not a connectivity failure: something answered.

      - A stale path prefix. Before the Tailscale Services migration these
        apps ran with UrlBase set, so any definition synced back then carries
        `/prowlarr` in the path and now misses the route. The forced sync
        above rewrites these.
      - An orphan. Delete an indexer in Prowlarr and re-add it — which is
        what fixing an indexer's categories often amounts to — and it comes
        back with a NEW id, while the *arr keeps its entry pointing at the
        old one. The forced sync above removes these itself (it runs with
        removeRemote=true), so one surviving here means Prowlarr could not
        reach that *arr, not that you need to delete it by hand.

    ONLY MEANINGFUL FOR SYNC-ENABLED APPS. If Prowlarr's connection for an
    *arr is disabled, that *arr's indexers are hand-managed on purpose — they
    are SUPPOSED to point straight at the indexer rather than at a Prowlarr
    proxy URL, and an empty list means nothing more than "not set up yet".
    Reporting either as a fault is how a deliberate configuration gets
    mistaken for a breakage, so the sync level is read first and drives
    everything below.

    Read-only on purpose. Deleting an *arr's indexers is never this script's
    call — we surface the mismatch and name the fix.
    """
    expected = "http://gluetun:9696/"

    # Prowlarr's sync level per app decides how to read each *arr's list.
    # Fetched once; a failure here degrades to "unknown", which suppresses the
    # verdicts rather than inventing them.
    levels = {}
    try:
        pbase, pkey = services["prowlarr"]
        for app in arr_get(pbase, pkey, "/api/v1/applications"):
            levels[str(app.get("name", "")).lower()] = app.get("syncLevel")
    except Exception as e:
        print(f"  ⚠ could not read Prowlarr's app connections: {e}")

    for name in ("radarr", "sonarr"):
        base, key = services[name]
        api_ver = "v3"
        try:
            indexers = arr_get(base, key, f"/api/{api_ver}/indexer")
        except Exception as e:
            print(f"  ⚠ {name}: could not list indexers: {e}")
            continue

        level = levels.get(name)
        if level == "disabled" or (name in levels and level is None):
            print(f"  · {name}: {len(indexers)} indexer(s); Prowlarr sync is "
                  "disabled for this app — hand-managed, nothing to reconcile")
            if not indexers:
                print(f"       {name} has NO indexers and Prowlarr will not add "
                      "any. Add them in its own UI, or re-enable the sync in "
                      "Prowlarr → Settings → Apps.")
            continue
        if name not in levels:
            print(f"  ⚠ {name}: Prowlarr has no app connection for it — "
                  "it will never receive indexers")
            continue

        if not indexers:
            print(f"  ⚠ {name}: no indexers despite sync being '{level}' — "
                  "check Prowlarr → Settings → Apps → Test, and that an "
                  "indexer's categories overlap this app's Sync Categories")
            continue
        bad = []
        for ix in indexers:
            url = next((f.get("value") for f in ix.get("fields", [])
                        if f.get("name") == "baseUrl"), "") or ""
            # Everything after the Prowlarr root must be exactly "<id>/" —
            # a leftover UrlBase makes it "prowlarr/<id>/" and misses.
            tail = url[len(expected):] if url.startswith(expected) else None
            if tail is None or not tail.rstrip("/").isdigit():
                bad.append((ix.get("name", "?"), url or "(unset)"))
        if bad:
            for ixname, url in bad:
                print(f"  ⚠ {name}: '{ixname}' → {url}")
            print(f"  ⚠ {name}: {len(bad)}/{len(indexers)} indexer(s) not on a "
                  "Prowlarr proxy URL — these are the 'doctype' test failures.")
            # Deliberately does NOT tell you to delete them. The forced sync
            # already removes what it owns, so anything still listed here is
            # either hand-added (deleting it loses a working indexer) or proof
            # Prowlarr cannot reach this *arr (deleting it changes nothing).
            print(f"       Check Prowlarr → Settings → Apps → {name.capitalize()} "
                  "→ Test. Do not delete these until that passes.")
        else:
            print(f"  ✓ {name}: {len(indexers)} indexer(s), all proxied by Prowlarr")

# ---------------------------------------------------------------------------
# Configure Plex: create libraries, trigger scan
# ---------------------------------------------------------------------------
def apply_plex_preferences(plex):
    """Set the server preferences docker-compose.yml used to pretend it set.

    The compose file carried fourteen PLEX_PREFERENCE_* environment variables
    and a comment claiming plexinc/pms-docker applies them to Preferences.xml
    on first boot. It does not — that image's first-run script handles only
    PLEX_UID, PLEX_GID, PLEX_CLAIM, ADVERTISE_IP, ALLOWED_NETWORKS and
    CHANGE_CONFIG_DIR_OWNERSHIP, and PLEX_PREFERENCE appears nowhere in the
    repository. So every one of them was silently ignored, most importantly
    the two that switch on NVENC — meaning the entire hardware-transcoding
    setup (the nvidia runtime, the Nvidia-Driver plugin, the VRAM reservation
    Ollama is built around) did nothing until somebody happened to tick the box
    in the Plex UI.

    This is the mechanism that actually works: authenticated PUT to /:/prefs,
    which is what the web UI itself calls. Runs on every bootstrap and is
    idempotent — setting a preference to its current value is a no-op.

    Deliberately NOT fatal. A rejected preference should not abort a bootstrap
    that has already created libraries; it is reported and the run continues.
    """
    prefs = {
        # The two that matter. Without these, Plex transcodes on CPU no matter
        # what the compose file or the driver plugin say.
        "TranscoderH264BackgroundPreset": "veryfast",
        "HardwareAcceleratedCodecs": 1,
        "HardwareAcceleratedEncoders": 1,
        # Privacy / noise, all previously inert.
        "CrashReportsOptedOut": 1,
        "PushNotificationsEnabled": 0,
        "RelayEnabled": 0,
        "DlnaEnabled": 0,
        # Library maintenance.
        "GenerateBIFBehavior": 1,
        "GenerateChapterThumbBehavior": 1,
        "MusicAnalysisBehavior": 1,
        "ScheduledLibraryUpdatesEnabled": 1,
        "ScheduledLibraryUpdateAt": 3,
    }
    ok, failed = 0, []
    for key, value in prefs.items():
        try:
            plex.settings.get(key).set(value)
            ok += 1
        except Exception as e:  # unknown key on this Plex version, or read-only
            failed.append(f"{key} ({type(e).__name__})")
    try:
        plex.settings.save()
        print(f"  ✓ Plex: applied {ok} server preferences (incl. NVENC on)")
    except Exception as e:
        print(f"  ⚠ Plex: could not save preferences: {e}")
        print("    Set Settings → Transcoder → 'Use hardware acceleration' by hand.")
        return
    if failed:
        print(f"    note: skipped {len(failed)} unknown/read-only: {', '.join(failed[:4])}")

    # Hardware transcoding also requires an active Plex Pass. The preference
    # sets cleanly without one and is then ignored at playback, which is why
    # this is worth saying out loud rather than leaving to a docs footnote.
    print("    (NVENC additionally requires an active Plex Pass on this account)")


def configure_plex(token: str, lan_ip: str):
    """Create libraries + trigger scan. Returns the connected PlexServer so
    downstream steps (Tautulli pre-seed) can reuse it, or None on failure."""
    try:
        from plexapi.server import PlexServer
        from plexapi.exceptions import BadRequest
    except ImportError:
        print("  ⚠ Plex: plexapi import failed after install — try re-running")
        return None

    try:
        plex = PlexServer(f"http://{lan_ip}:32400", token)
    except Exception as e:
        print(f"  ⚠ Plex: could not connect: {e}")
        print("    Check PLEX_LAN_IP and PLEX_TOKEN in .env")
        return None

    apply_plex_preferences(plex)

    existing = {s.title for s in plex.library.sections()}

    for name, ltype, path, agent, scanner in [
        ("Movies",   "movie",  "/data/media/movies", "tv.plex.agents.movie",  "Plex Movie"),
        ("TV Shows", "show",   "/data/media/tv",      "tv.plex.agents.series", "Plex TV Series"),
        ("Music",    "artist", "/data/media/music",   "tv.plex.agents.music",  "Plex Music"),
    ]:
        if name in existing:
            print(f"  ✓ Plex: '{name}' already exists")
            continue
        try:
            # The new tv.plex.agents.* agents require BCP-47 locale tags
            # (en-US, en-GB, …); the legacy two-letter form ("en") returns
            # 400 'language' is invalid.
            plex.library.add(name=name, type=ltype, agent=agent,
                             scanner=scanner, location=path, language="en-US")
            print(f"  ✓ Plex: created library '{name}'")
        except BadRequest as e:
            print(f"  ⚠ Plex: could not create '{name}': {e}")

    for section in plex.library.sections():
        section.update()
    print("  ✓ Plex: library scan triggered")
    return plex

# ---------------------------------------------------------------------------
# Configure Tautulli: skip its first-run wizard by pre-seeding PMS fields
# ---------------------------------------------------------------------------
def configure_tautulli(plex, token: str) -> None:
    """Pre-seed Tautulli's PMS connection so the first-run wizard is skipped.

    config.ini is bind-mounted from ${STACK_DIR}/configs/tautulli/config.ini
    to /config/config.ini inside the container (see docker-compose.yml).
    Rewriting the host file in-place preserves the inode so the bind mount
    stays pointed at the right content. A docker restart picks it up.

    `plex` is a connected plexapi.PlexServer; we pull machineIdentifier and
    friendlyName straight off it. `token` is passed explicitly because
    plexapi stores it as a private attribute and we'd rather not rely on
    that stability.
    """
    import configparser

    config_path = STACK_DIR / "configs" / "tautulli" / "config.ini"
    if not config_path.exists():
        print(f"  ⚠ Tautulli: {config_path} missing — run generate-configs.py first")
        return

    cfg = configparser.ConfigParser()
    cfg.read(config_path)

    if cfg.has_option("General", "first_run_complete") and \
       cfg.get("General", "first_run_complete") == "1":
        print("  ✓ Tautulli: first-run already complete")
        return

    if not cfg.has_section("General"):
        cfg.add_section("General")
    if not cfg.has_section("PMS"):
        cfg.add_section("PMS")

    cfg.set("General", "first_run_complete", "1")
    # Tautulli talks to Plex over the frontend docker network — container DNS
    # name "plex" resolves to the PMS container's IP on that bridge.
    cfg.set("PMS", "pms_ip",         "plex")
    cfg.set("PMS", "pms_port",       "32400")
    cfg.set("PMS", "pms_ssl",        "0")
    cfg.set("PMS", "pms_is_cloud",   "0")
    cfg.set("PMS", "pms_is_remote",  "0")
    cfg.set("PMS", "pms_url_manual", "0")
    cfg.set("PMS", "pms_identifier", plex.machineIdentifier)
    cfg.set("PMS", "pms_name",       plex.friendlyName)
    cfg.set("PMS", "pms_token",      token)

    # Truncate-in-place so the bind-mounted inode survives.
    with open(config_path, "w") as f:
        cfg.write(f)
    config_path.chmod(0o600)
    print(f"  ✓ Tautulli: seeded PMS connection → {plex.friendlyName}")

    try:
        subprocess.run(
            ["docker", "restart", "tautulli"],
            check=True, capture_output=True, text=True,
        )
        print("  ✓ Tautulli: restarted to pick up new config")
    except subprocess.CalledProcessError as e:
        print(f"  ⚠ Tautulli: restart failed: {e.stderr.strip()[:200]}")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Wire the homeserver stack together via API after first boot."
    )
    p.add_argument(
        "--stack-dir", type=Path,
        help="Override the homeserver/ directory (default: inferred from script location)"
    )
    p.add_argument(
        "--timeout", type=int, default=180,
        help="Per-service wait timeout in seconds (default: 180)"
    )
    return p.parse_args()


def main() -> None:
    global STACK_DIR, ENV_FILE, GENERATED_FILE, DOCKER_ENV
    args = _parse_args()
    if args.stack_dir:
        STACK_DIR = args.stack_dir.resolve()
        ENV_FILE = STACK_DIR / ".env"
        GENERATED_FILE = STACK_DIR / "generated.env"
        DOCKER_ENV = STACK_DIR / ".env.docker"

    env = load_env()
    lan_ip = require(env, "PLEX_LAN_IP")
    sabnzbd_key = require(env, "SABNZBD_API_KEY")

    # Every *arr serves at root now (UrlBase stripped). bootstrap.py still
    # talks to them on localhost:<port> because the host port-publishes
    # them on 127.0.0.1 — Tailscale Services are tailnet ingress, not internal calls.
    SERVICES = {
        "radarr":   ("http://localhost:7878",   require(env, "RADARR_API_KEY")),
        "sonarr":   ("http://localhost:8989",   require(env, "SONARR_API_KEY")),
        "prowlarr": ("http://localhost:9696",   require(env, "PROWLARR_API_KEY")),
    }

    print("\n=== Waiting for services ===\n")
    wait_for("http://localhost:8080/api?mode=version", "sabnzbd",
             timeout=args.timeout)
    for name, (url, _key) in SERVICES.items():
        api_ver = "v1" if name == "prowlarr" else "v3"
        wait_for(f"{url}/api/{api_ver}/system/status", name, timeout=args.timeout)
    wait_for("http://localhost:5055", "seerr", timeout=args.timeout)

    print("\n=== Radarr ===\n")
    url, key = SERVICES["radarr"]
    configure_arr("Radarr", url, key, "/data/media/movies", "movies", sabnzbd_key)

    print("\n=== Sonarr ===\n")
    url, key = SERVICES["sonarr"]
    configure_arr("Sonarr", url, key, "/data/media/tv", "tv", sabnzbd_key,
                  extra_mm={"createEmptySeriesFolders": False})

    print("\n=== Prowlarr ===\n")
    url, key = SERVICES["prowlarr"]
    configure_prowlarr(url, key, env)

    # After the forced sync, confirm from the *arr side that what landed there
    # is actually usable. Prowlarr reporting a successful sync and the *arr
    # holding a URL that 404s into Prowlarr's web UI are not mutually
    # exclusive — orphaned definitions survive every sync untouched.
    print("\n=== Synced indexers ===\n")
    check_synced_indexers(SERVICES)

    print("\n=== Plex ===\n")
    plex_token = get(env, "PLEX_TOKEN")
    if not plex_token:
        print("  Plex token not found in .env.")
        print(f"  1. Open http://{lan_ip}:32400/web in your browser")
        print("  2. Sign in with your Plex account")
        print("  3. Settings → General → scroll to bottom → click 'Show'")
        print("  4. Copy the X-Plex-Token value\n")
        # getpass suppresses terminal echo and keeps the token out of shell history.
        plex_token = getpass.getpass("  Paste PLEX_TOKEN here (or press Enter to skip): ").strip()
        if plex_token:
            write_generated({"PLEX_TOKEN": plex_token})
            refresh_docker_env()
            print("  ✓ PLEX_TOKEN saved to generated.env\n")

    plex = None
    if plex_token:
        plex = configure_plex(plex_token, lan_ip)
        # PLEX_CLAIM tokens are single-use and expire after ~4 minutes.
        # Once we've got a PLEX_TOKEN the claim is spent — blank it so a later
        # redeploy doesn't feed a dead claim into a freshly-recreated Plex.
        if get(env, "PLEX_CLAIM"):
            write_generated({"PLEX_CLAIM": ""})
            refresh_docker_env()
            print("  ✓ PLEX_CLAIM cleared (one-time-use, already consumed)")
    else:
        print("  ⚠ Skipped — re-run this script after signing into Plex")

    print("\n=== Tautulli ===\n")
    if plex is not None:
        configure_tautulli(plex, plex_token)
    else:
        print("  ⚠ Skipped — needs a working Plex connection from the previous step")

    print("\n=== Done ===\n")
    print("Stack is fully configured. Each admin UI is a Tailscale Service")
    print("with its own MagicDNS name and a real certificate. Publish them with")
    print("`tailscale serve --service=svc:<name> --bg 127.0.0.1:<port>` — see")
    print("docs/deployment.md step 6.5. Plex is fronted by nothing.")
    print()
    print("  SABnzbd:   https://sab.<tailnet>.ts.net")
    print("  Prowlarr:  https://prowlarr.<tailnet>.ts.net")
    print("  Radarr:    https://radarr.<tailnet>.ts.net")
    print("  Sonarr:    https://sonarr.<tailnet>.ts.net")
    print("  Bazarr:    https://bazarr.<tailnet>.ts.net")
    print("  Tautulli:  https://tautulli.<tailnet>.ts.net")
    print("  Profilarr: https://profilarr.<tailnet>.ts.net")
    print("  Seerr:     https://seerr.<tailnet>.ts.net")
    print(f"  Plex:      http://{lan_ip}:32400/web   (public — direct)")
    print()
    print("  MagicDNS usually puts the tailnet domain in the DNS search path,")
    print("  so bare https://radarr/ resolves too.")
    print()
    print("  Unraid GUI — depends on NOTHING above: not Docker, not a service")
    print("  advertisement. Works with the array stopped. This is the emergency")
    print("  path, and on Unraid stopping the array stops Docker, so it matters:")
    print(f"    http://{lan_ip}/            (LAN)")
    tailnet_host = get(env, "TAILNET_HOST_IP")
    if tailnet_host:
        print(f"    http://{tailnet_host}/         (over Tailscale)")
    print()
    print("  Every backend also stays on 127.0.0.1:<port>. That is both what")
    print("  tailscale serve proxies to and your fallback if ingress breaks:")
    print("    ssh -L 7878:127.0.0.1:7878 root@<server>")
    print()
    print("Remaining manual steps:")
    print("  1. Plex → Settings → Transcoder → Use hardware acceleration when")
    print("     available → select NVIDIA GeForce RTX 3050 (requires Plex Pass —")
    print("     cannot be set via API).")
    print("  2. Seerr → sign in with your Plex account, then Settings → Users →")
    print("     edit each family member → grant 'Auto-Request' so their Plex")
    print("     Watchlist additions become Radarr/Sonarr requests automatically.")
    print("     (Per-user grant; Seerr ties it to each Plex SSO identity.)")
    print("  3. Profilarr → https://profilarr.<tailnet>.ts.net → add Radarr +")
    print("     Sonarr as sync")
    print("     targets (paste URLs + API keys from generated.env), subscribe to")
    print("     the Dictionarry DB and/or TRaSH Guides, select profiles, sync.")
    print("     Profilarr has no API-driven bootstrap path.")
    print("  4. Ollama ships with no models. Pull one:")
    print("       docker exec ollama ollama pull llama3.2:3b")
    print("     Keep models under ~4 GB so they coexist with a Plex transcode")
    print("     on the 6 GB card. See docs/software.md#local-ai for sizing.")

if __name__ == "__main__":
    main()
