#!/usr/bin/env python3
"""
generate-configs.py
===================
Interactive setup script. Run once before starting the stack.

  cd /mnt/user/appdata/homeserver/homeserver
  python3 scripts/generate-configs.py

What it does:
  1. Prompts for any credentials not yet in .env, writes them back
  2. Auto-generates STACK_DIR and UUID API keys into generated.env
  3. Writes a merged .env.docker (convenience single-file env for `docker compose --env-file`)
  4. Writes all app config files to configs/ so no setup wizard is needed
  5. Creates the /mnt/user/data/ directory structure

Two env files:
  .env          — what you type (credentials, settings)
  generated.env — what the script writes (API keys, paths, tokens)

Safe to re-run — skips prompts for values already set, won't overwrite
existing API keys, and mkdir -p is idempotent.

Uses only stdlib — no pip dependencies.
"""

import argparse
import ipaddress
import json
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Callable, Optional

# ---------------------------------------------------------------------------
# Paths — derived from script location, not hardcoded
# ---------------------------------------------------------------------------
STACK_DIR: Path      = Path(__file__).resolve().parent.parent   # homeserver/
ENV_FILE: Path       = STACK_DIR / ".env"           # user-edited credentials
GENERATED_FILE: Path = STACK_DIR / "generated.env"  # machine-written, gitignored
DOCKER_ENV: Path     = STACK_DIR / ".env.docker"    # merged, single-file env
CONFIGS: Path        = STACK_DIR / "configs"

# ---------------------------------------------------------------------------
# .env loader / writer
# ---------------------------------------------------------------------------
def _parse_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                val = val.split("#")[0].strip()
                env[key.strip()] = val
    return env

def load_env(*paths: Path) -> dict:
    """Load and merge one or more env files. Later files win on conflict."""
    env = {}
    for path in paths:
        if not path.exists():
            continue
        env.update(_parse_env_file(path))
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found.")
        print(f"  cp {ENV_FILE.parent}/.env.example {ENV_FILE}")
        sys.exit(1)
    return env

def write_back_to_env(path: Path, updates: dict):
    """Update existing keys in path in place; append any not found."""
    lines = path.read_text().splitlines(keepends=True) if path.exists() else []
    found = set()
    out = []
    for line in lines:
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.partition("=")[0].strip()
            if key in updates:
                out.append(f"{key}={updates[key]}\n")
                found.add(key)
                continue
        out.append(line)
    for key, val in updates.items():
        if key not in found:
            out.append(f"{key}={val}\n")
    path.write_text("".join(out))
    path.chmod(0o600)

def write_generated(updates: dict):
    """Write (or update) generated.env with machine-generated values."""
    existing = _parse_env_file(GENERATED_FILE) if GENERATED_FILE.exists() else {}
    existing.update(updates)
    lines = ["# Auto-generated by scripts — do not edit by hand\n"]
    for k, v in existing.items():
        lines.append(f"{k}={v}\n")
    GENERATED_FILE.write_text("".join(lines))
    GENERATED_FILE.chmod(0o600)

def write_merged_docker_env():
    """Write .env.docker = .env + generated.env merged — convenience for tooling that takes a single --env-file."""
    merged = {}
    for path in (ENV_FILE, GENERATED_FILE):
        if path.exists():
            merged.update(_parse_env_file(path))
    lines = ["# Merged env — auto-generated, do not edit\n"]
    for k, v in merged.items():
        lines.append(f"{k}={v}\n")
    DOCKER_ENV.write_text("".join(lines))
    DOCKER_ENV.chmod(0o600)

# ---------------------------------------------------------------------------
# Input validators
# Each returns the validated value, or raises ValueError with a user-facing
# message. ask() catches the error and reprompts.
# ---------------------------------------------------------------------------
ZONEINFO = Path("/usr/share/zoneinfo")

def validate_tz(val: str) -> str:
    # /usr/share/zoneinfo exists on every Unraid host and every modern Linux.
    # On platforms where it doesn't (e.g. running this script on macOS for
    # testing), skip validation rather than rejecting every timezone.
    if ZONEINFO.exists() and not (ZONEINFO / val).is_file():
        raise ValueError(f"not a valid timezone (no {ZONEINFO}/{val})")
    return val

def validate_ip(val: str) -> str:
    try:
        ipaddress.ip_address(val)
    except ValueError as e:
        raise ValueError(f"not a valid IP address: {e}") from e
    return val

def validate_cidr(val: str) -> str:
    try:
        ipaddress.ip_network(val, strict=False)
    except ValueError as e:
        raise ValueError(f"not a valid CIDR: {e}") from e
    return val

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------
def ask(label: str, default: str = "", hint: str = "",
        validator: Optional[Callable[[str], str]] = None) -> str:
    """Prompt until a non-empty value is entered and (optionally) validates.
    Returns default if provided and input is blank.
    """
    if hint:
        print(f"    {hint}")
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {label}{suffix}: ").strip()
        if not val and default:
            val = default
        if not val:
            print("    Required.")
            continue
        if validator is not None:
            try:
                return validator(val)
            except ValueError as e:
                print(f"    Invalid: {e}")
                continue
        return val

def prompt_for_missing(env: dict) -> dict:
    """
    Prompt for any missing required values. Returns a dict of new values
    collected — caller is responsible for merging into env and writing back.
    """
    updates = {}

    def get_or_ask(key: str, label: str, default: str = "", hint: str = "",
                   validator: Optional[Callable[[str], str]] = None) -> str:
        val = env.get(key, "").strip()
        if val:
            return val
        val = ask(label, default=default, hint=hint, validator=validator)
        updates[key] = val
        return val

    missing = [
        k for k in [
            "TZ", "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
            "VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY",
            "USENET_HOST", "USENET_USER", "USENET_PASS",
            "NZBGEEK_API_KEY", "NZBPLANET_API_KEY",
        ]
        if not env.get(k, "").strip()
    ]

    if not missing:
        return updates  # nothing to ask

    print("\nSome required values are missing from .env. Let's fill them in.\n")

    # System
    if "TZ" in missing:
        print("--- System ---")
        get_or_ask("TZ", "Timezone",
                   default="America/Los_Angeles",
                   hint="e.g. America/New_York, America/Los_Angeles, Europe/London",
                   validator=validate_tz)

    # Network / Plex
    net_missing = [k for k in ["PLEX_LAN_IP", "PLEX_LAN_SUBNET"] if k in missing]
    if net_missing:
        print("\n--- Network ---")
        if "PLEX_LAN_IP" in missing:
            get_or_ask("PLEX_LAN_IP", "Server LAN IP",
                       hint="shown in Unraid UI top-right corner, e.g. 192.168.1.50",
                       validator=validate_ip)
        if "PLEX_LAN_SUBNET" in missing:
            get_or_ask("PLEX_LAN_SUBNET", "LAN subnet (CIDR)",
                       hint="e.g. 192.168.1.0/24  — run: ip route | grep default",
                       validator=validate_cidr)

    # Mullvad WireGuard — for Gluetun outbound VPN on SAB + Prowlarr
    vpn_missing = [k for k in ["VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY"] if k in missing]
    if vpn_missing:
        print("\n--- Mullvad WireGuard (Gluetun outbound VPN) ---")
        print("  Generate a config at mullvad.net/account → WireGuard configuration.")
        if "VPN_PRIVATE_KEY" in missing:
            get_or_ask("VPN_PRIVATE_KEY", "WireGuard private key",
                       hint="from [Interface] PrivateKey = ... in the downloaded .conf")
        if "VPN_ADDRESS" in missing:
            get_or_ask("VPN_ADDRESS", "WireGuard address",
                       hint="from [Interface] Address = ... (comma-separated v4,v6)")
        if "VPN_CITY" in missing:
            get_or_ask("VPN_CITY", "Exit city",
                       default="Amsterdam",
                       hint="pick one near your Usenet provider for lowest latency")

    # Usenet
    usenet_missing = [k for k in ["USENET_HOST", "USENET_USER", "USENET_PASS"] if k in missing]
    if usenet_missing:
        print("\n--- Usenet (primary provider) ---")
        get_or_ask("USENET_HOST", "Provider hostname", hint="e.g. news.newshosting.com")
        get_or_ask("USENET_USER", "Username")
        get_or_ask("USENET_PASS", "Password")
        if not env.get("USENET_CONNECTIONS", "").strip():
            val = ask("Max connections", default="20", hint="check your plan — Newshosting Unlimited = 30+")
            if val != "20":
                updates["USENET_CONNECTIONS"] = val

    # Optional fill server
    fill_keys = ["USENET_FILL_HOST", "USENET_FILL_USER", "USENET_FILL_PASS"]
    has_fill = any(env.get(k, "").strip() for k in fill_keys)
    if not has_fill:
        ans = input("\n  Add a fill/backup Usenet server (different backbone)? [y/N]: ").strip().lower()
        if ans == "y":
            updates["USENET_FILL_HOST"] = ask("Fill server hostname")
            updates["USENET_FILL_USER"] = ask("Fill server username")
            updates["USENET_FILL_PASS"] = ask("Fill server password")

    # Indexers
    idx_missing = [k for k in ["NZBGEEK_API_KEY", "NZBPLANET_API_KEY"] if k in missing]
    if idx_missing:
        print("\n--- Indexers ---")
        if "NZBGEEK_API_KEY" in missing:
            get_or_ask("NZBGEEK_API_KEY", "NZBGeek API key", hint="nzbgeek.info → My Profile → API Key")
        if "NZBPLANET_API_KEY" in missing:
            get_or_ask("NZBPLANET_API_KEY", "NZBPlanet API key", hint="nzbplanet.net → My Account → API Key")

    # Plex server name (optional, has default)
    if not env.get("PLEX_SERVER_NAME", "").strip():
        print("\n--- Plex ---")
        val = ask("Plex server name (shown in clients)", default="Home Media Server")
        if val != "Home Media Server":
            updates["PLEX_SERVER_NAME"] = val

    return updates


# ---------------------------------------------------------------------------
# Config writers
# ---------------------------------------------------------------------------
_PRESERVE_USER_EDITS = True
_PENDING_NEW_FILES: list[Path] = []

def _write_secret(path: Path, content: str) -> None:
    """Write a config file that contains credentials or API keys. Mode 0600
    so only the owner (nobody on Unraid, after chown) can read it.

    If the target file already exists and its content differs from what we
    want to write, the new template is written alongside as <path>.new and
    the existing file is left untouched. This preserves user customizations
    made through a service's own UI (e.g. additional Radarr custom formats)
    on re-runs of generate-configs.py. Matches the Debian/Unraid convention
    for handling package-owned config files that may have been edited. main()
    prints a summary at the end for every `.new` file produced, so they're
    hard to miss.

    The .new-on-conflict behavior can be disabled with --force-overwrite.
    """
    if path.exists() and _PRESERVE_USER_EDITS:
        if path.read_text() == content:
            path.chmod(0o600)
            return
        new_path = path.with_suffix(path.suffix + ".new")
        new_path.write_text(content)
        new_path.chmod(0o600)
        _PENDING_NEW_FILES.append(path)
        print(f"    ! existing file preserved; new template at {new_path.name}")
        return
    path.write_text(content)
    path.chmod(0o600)

def write_sabnzbd(env: dict):
    dest = CONFIGS / "sabnzbd"
    dest.mkdir(parents=True, exist_ok=True)

    api_key  = env["SABNZBD_API_KEY"]
    host     = env["USENET_HOST"]
    port     = env.get("USENET_PORT", "563")
    ssl      = env.get("USENET_SSL", "1")
    user     = env["USENET_USER"]
    password = env["USENET_PASS"]
    conns    = env.get("USENET_CONNECTIONS", "20")

    fill_host  = env.get("USENET_FILL_HOST", "")
    fill_user  = env.get("USENET_FILL_USER", "")
    fill_pass  = env.get("USENET_FILL_PASS", "")
    fill_conns = env.get("USENET_FILL_CONNECTIONS", "10")

    fill_block = ""
    if fill_host and fill_user and fill_pass:
        fill_block = f"""
    [[server2]]
    displayname = Fill Server
    host = {fill_host}
    port = 563
    ssl = 1
    ssl_verify = 2
    username = {fill_user}
    password = {fill_pass}
    connections = {fill_conns}
    priority = 1
    retention = 0
    timeout = 60
    required = 0
    optional = 1
    enabled = 1"""

    content = f"""[misc]
host = 0.0.0.0
port = 8080
url_base = /sabnzbd
# host_whitelist blocks requests from hostnames not listed here. SAB is
# reachable only via Tailscale (no public URL) — localhost + service name
# covers Gluetun-internal health checks and admin access. Add more comma-
# separated entries (e.g. your Tailscale MagicDNS hostname) as needed.
host_whitelist = localhost,sabnzbd,gluetun,mediaserver.local
api_key = {api_key}
nzo_ids = {api_key}
wizard_step = 10
language = en
cherryhost = 0.0.0.0
cherryport = 8080
download_dir = /incomplete
complete_dir = /data/usenet/complete
log_dir = /config/logs
admin_dir = /config/admin
# 0 = unlimited. Set to your connection speed in KB/s to cap usage.
# 100Mbps=12500  250Mbps=31250  500Mbps=62500  1Gbps=125000
bandwidth_max = 0
bandwidth_perc = 100
direct_unpack = 1
pause_on_post_processing = 0
enable_par_cleanup = 1
cleanup_list = .nfo, .sfv, .jpg, .png, .nzb
fail_on_fail = 0
history_retention = 30
history_limit = 200
dupl_priority = -100
check_new_rel = 0
enable_broadcast = 0
keep_awake = 1
send_group = 0

[notifications]
ntf_enable = 0

[servers]

    [[server1]]
    displayname = Primary Provider
    host = {host}
    port = {port}
    ssl = {ssl}
    ssl_verify = 2
    username = {user}
    password = {password}
    connections = {conns}
    priority = 0
    retention = 0
    timeout = 60
    required = 0
    optional = 0
    enabled = 1
{fill_block}

[categories]

    [[movies]]
    name = movies
    dir = movies
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[tv]]
    name = tv
    dir = tv
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[music]]
    name = music
    dir = music
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[*]]
    name = *
    dir =
    pp = 3
    script = None
    priority = -100
    req_completion_rate = 100.0
    newzbin =
"""
    _write_secret(dest / "sabnzbd.ini", content)
    print("  ✓ configs/sabnzbd/sabnzbd.ini")

def write_arr_config(name: str, port: int, api_key: str, url_base: str):
    dest = CONFIGS / name
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""<Config>
  <BindAddress>*</BindAddress>
  <Port>{port}</Port>
  <SslPort>{port + 1000}</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>False</LaunchBrowser>
  <ApiKey>{api_key}</ApiKey>
  <AuthenticationMethod>Forms</AuthenticationMethod>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <Branch>main</Branch>
  <LogLevel>info</LogLevel>
  <UrlBase>{url_base}</UrlBase>
  <UpdateMechanism>Docker</UpdateMechanism>
</Config>
"""
    _write_secret(dest / "config.xml", content)
    print(f"  ✓ configs/{name}/config.xml")

def write_seerr(env: dict):
    """Write Seerr's settings.json.

    Seerr is the actively-maintained successor to Overseerr (Overseerr +
    Jellyseerr lineage). Its settings schema is largely a superset of
    Overseerr's — the keys below are Overseerr-compatible and accepted by
    Seerr. Plex Watchlist auto-request is enabled by default so family
    members can "Add to Watchlist" in the Plex app and have Seerr submit
    the request on their behalf.
    """
    dest = CONFIGS / "seerr"
    dest.mkdir(parents=True, exist_ok=True)

    lan_ip = env["PLEX_LAN_IP"]

    settings = {
        "apiKey": uuid.uuid4().hex,
        "main": {
            "apiKey": uuid.uuid4().hex,
            "applicationTitle": "Media Requests",
            # Admin-only; Seerr reachable via Tailscale MagicDNS.
            "applicationUrl": "",
            "trustProxy": False,
            "hideAvailable": False,
            "localLogin": False,
            "newPlexLogin": True,
            # REQUEST + AUTO_APPROVE + AUTO_REQUEST for Watchlist flow.
            "defaultPermissions": 32,
            "defaultQuotas": {
                "movie": {"quotaLimit": 0, "quotaDays": 7},
                "tv":    {"quotaLimit": 0, "quotaDays": 7}
            },
            "partialRequestsEnabled": True,
            "locale": "en"
        },
        "plex": {
            "name": env.get("PLEX_SERVER_NAME", "Home Media Server"),
            "ip": lan_ip,
            "port": 32400,
            "useSsl": False,
            "libraries": [],
            # Poll Plex Watchlist every 5 min for auto-request.
            "webAppUrl": ""
        },
        "tautulli": None,
        "radarr": [],
        "sonarr": [],
        "public": {"initialized": False},
        "notifications": {
            "agents": {
                "email":      {"enabled": False, "types": 0, "options": {}},
                "discord":    {"enabled": False, "types": 0, "options": {}},
                "slack":      {"enabled": False, "types": 0, "options": {}},
                "telegram":   {"enabled": False, "types": 0, "options": {}},
                "pushbullet": {"enabled": False, "types": 0, "options": {}},
                "pushover":   {"enabled": False, "types": 0, "options": {}},
                "lunasea":    {"enabled": False, "types": 0, "options": {}},
                "gotify":     {"enabled": False, "types": 0, "options": {}},
                "ntfy":       {"enabled": False, "types": 0, "options": {}},
                "webpush":    {"enabled": False, "types": 0, "options": {}}
            }
        },
        "jobs": {
            "plex-watchlist-sync": {
                "schedule": "0 */2 * * * *"
            }
        }
    }

    _write_secret(dest / "settings.json", json.dumps(settings, indent=2))
    print("  ✓ configs/seerr/settings.json")

def write_recyclarr(env: dict):
    """Write recyclarr.yml pulling the TRaSH-Guides HD Bluray + WEB templates
    for Radarr and Sonarr. The `include:` lines reference upstream template
    files in the Recyclarr configs repo, so TRaSH updates land automatically
    on the next scheduled sync (CRON_SCHEDULE in compose, Monday 5am).

    API keys are read at runtime from the container environment (the compose
    service passes RADARR_API_KEY / SONARR_API_KEY through), so this file
    contains no secrets and is written world-readable at /app/config/...

    The destination lives in /mnt/user/appdata/recyclarr/ so Recyclarr reads
    it directly on start — no separate bind-mount needed.
    """
    dest = Path("/mnt/user/appdata/recyclarr")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)

    content = """\
# Recyclarr config — TRaSH-Guides HD Bluray + WEB profile for 1080p.
# Regenerated by scripts/generate-configs.py. Add custom sections below
# the generated block; they'll be preserved on re-run via the .new-file
# mechanism.

radarr:
  radarr-main:
    base_url: http://radarr:7878/radarr
    api_key: !env_var RADARR_API_KEY

    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

sonarr:
  sonarr-main:
    base_url: http://sonarr:8989/sonarr
    api_key: !env_var SONARR_API_KEY

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

    delete_old_custom_formats: true
    replace_existing_custom_formats: true
"""
    target = dest / "recyclarr.yml"
    if target.exists() and target.read_text() != content and _PRESERVE_USER_EDITS:
        new_target = target.with_suffix(".yml.new")
        new_target.write_text(content)
        _PENDING_NEW_FILES.append(new_target)
        print(f"  ! {target} differs — wrote {new_target.name} alongside")
    else:
        target.write_text(content)
        subprocess.run(["chown", "nobody:users", str(target)], check=False)
        target.chmod(0o644)
        print(f"  ✓ {target}")

def write_bazarr(env: dict):
    dest = CONFIGS / "bazarr"
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""[general]
ip = 0.0.0.0
port = 6767
base_url = /bazarr
launch_browser = False
update_upgrade = False
timezone = {env.get("TZ", "UTC")}

[auth]
type = None

[sonarr]
ip = sonarr
port = 8989
base_url = /sonarr
ssl = False
apikey = {env["SONARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[radarr]
ip = radarr
port = 7878
base_url = /radarr
ssl = False
apikey = {env["RADARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[subliminal]
hearing_impaired_subtitles = False
single_language = False

[opensubtitles]
enabled = False
username =
password =

[languages]
single = False
subtitles_languages = ['en']
enabled_codecs = ['utf-8']
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/bazarr/config.ini")

def write_tautulli(env: dict):
    """Pre-seed Tautulli config.ini with HTTP settings + API key.

    PMS connection (server token, identifier) is left to Tautulli's first-run
    wizard — it's a ~30-second flow and needs PLEX_TOKEN which may not be
    captured until bootstrap.py runs interactively.
    """
    dest = CONFIGS / "tautulli"
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""[General]
api_key = {env["TAUTULLI_API_KEY"]}
http_host = 0.0.0.0
http_port = 8181
http_root = /
launch_browser = 0
check_github = 0
enable_plex_update_notify = 0

[Monitoring]
refresh_libraries_on_startup = 0
refresh_users_on_startup = 0
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/tautulli/config.ini")

# ---------------------------------------------------------------------------
# Data directory creation
# ---------------------------------------------------------------------------
def create_data_dirs():
    dirs = [
        # Incomplete downloads live on a cache-only share — setup-unraid.sh
        # provisions /boot/config/shares/usenet-incomplete.cfg with
        # shareUseCache=only so mover never migrates these files to the array.
        Path("/mnt/user/usenet-incomplete"),
        Path("/mnt/user/data/usenet/complete/movies"),
        Path("/mnt/user/data/usenet/complete/tv"),
        Path("/mnt/user/data/usenet/complete/music"),
        Path("/mnt/user/data/media/movies"),
        Path("/mnt/user/data/media/tv"),
        Path("/mnt/user/data/media/music"),
        Path("/mnt/user/appdata/plex-transcode"),
    ]
    created = [d for d in dirs if not d.exists()]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    if created:
        subprocess.run(["chown", "-R", "nobody:users", "/mnt/user/data/"], check=False)
        for d in created:
            print(f"  ✓ created {d}")
    else:
        print("  ✓ data directories already exist")

    # Seed Seerr's settings.json into appdata directly. Seerr owns the whole
    # /app/config directory once running, so we can't bind-mount a single host
    # file into it cleanly — we drop the seed template into appdata and let
    # the container pick it up on first start. Owned by nobody:users (99:100),
    # matching the `user:` override on the seerr service in compose.
    seerr_appdata = Path("/mnt/user/appdata/seerr")
    seerr_appdata.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(seerr_appdata)], check=False)
    seed = CONFIGS / "seerr" / "settings.json"
    target = seerr_appdata / "settings.json"
    if seed.exists() and not target.exists():
        target.write_bytes(seed.read_bytes())
        subprocess.run(["chown", "nobody:users", str(target)], check=False)
        target.chmod(0o600)
        print(f"  ✓ seeded {target}")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Interactive setup: writes .env + generated.env + per-service configs."
    )
    p.add_argument(
        "--stack-dir", type=Path,
        help="Override the homeserver/ directory (default: inferred from script location)"
    )
    p.add_argument(
        "--force-overwrite", action="store_true",
        help="Overwrite existing config files instead of writing a .new alongside."
    )
    return p.parse_args()


def main() -> None:
    global STACK_DIR, ENV_FILE, GENERATED_FILE, DOCKER_ENV, CONFIGS, _PRESERVE_USER_EDITS
    args = _parse_args()
    if args.stack_dir:
        STACK_DIR = args.stack_dir.resolve()
        ENV_FILE = STACK_DIR / ".env"
        GENERATED_FILE = STACK_DIR / "generated.env"
        DOCKER_ENV = STACK_DIR / ".env.docker"
        CONFIGS = STACK_DIR / "configs"
    _PRESERVE_USER_EDITS = not args.force_overwrite

    print(f"Stack directory: {STACK_DIR}\n")

    # Load both files — generated.env may not exist yet on first run
    env = load_env(ENV_FILE, GENERATED_FILE)

    # Step 1: Interactively collect any missing credentials → .env
    new_values = prompt_for_missing(env)
    if new_values:
        env.update(new_values)
        write_back_to_env(ENV_FILE, new_values)
        print("\n  .env updated.\n")

    # Step 2: Generate any missing machine values → generated.env
    api_key_fields = [
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY", "TAUTULLI_API_KEY",
    ]
    auto = {}
    if not env.get("STACK_DIR", "").strip():
        auto["STACK_DIR"] = str(STACK_DIR)
    for k in api_key_fields:
        if not env.get(k, "").strip():
            auto[k] = uuid.uuid4().hex
    if auto:
        env.update(auto)
        write_generated(auto)
        print("Generated and saved to generated.env:")
        for k in auto:
            print(f"  {k}")
        print()

    # Step 3: Write merged .env.docker (single-file env for docker compose)
    write_merged_docker_env()

    # Step 4: Final validation — everything required must now be set.
    required = [
        "TZ", "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
        "VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY",
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY",
        "USENET_HOST", "USENET_USER", "USENET_PASS",
        "NZBGEEK_API_KEY", "NZBPLANET_API_KEY",
    ]
    missing = [k for k in required if not env.get(k, "").strip()]
    if missing:
        print("ERROR: These required values are still not set:")
        for k in missing:
            print(f"  {k}")
        sys.exit(1)

    # Step 5: Write app configs.
    print("\nWriting config files...")
    write_sabnzbd(env)
    write_arr_config("radarr",   7878, env["RADARR_API_KEY"],  "/radarr")
    write_arr_config("sonarr",   8989, env["SONARR_API_KEY"],  "/sonarr")
    write_arr_config("lidarr",   8686, env["LIDARR_API_KEY"],  "/lidarr")
    write_arr_config("prowlarr", 9696, env["PROWLARR_API_KEY"],"/prowlarr")
    write_seerr(env)
    write_recyclarr(env)
    write_bazarr(env)
    write_tautulli(env)

    # Step 6: Create data directories.
    print("\nCreating data directories...")
    create_data_dirs()

    if _PENDING_NEW_FILES:
        print("\n" + "-" * 60)
        print("Existing configs preserved; new templates written alongside:")
        for p in _PENDING_NEW_FILES:
            print(f"  diff {p} {p}.new")
        print("Reconcile (or delete the .new files) before starting the stack.")
        print("Re-run with --force-overwrite to replace existing files instead.")
        print("-" * 60)

    print(f"""
Done.

Next steps:
  1. Start the stack:
       docker compose --env-file .env --env-file generated.env up -d
  2. Wait ~60s for containers to initialise.
  3. python3 scripts/bootstrap.py
""")

if __name__ == "__main__":
    main()
