#!/usr/bin/env python3
"""
generate-configs.py
===================
Interactive setup script. Run once before starting the stack.

  cd /mnt/user/appdata/homeserver/homeserver
  python3 scripts/generate-configs.py

What it does:
  1. Prompts for any credentials not yet in .env, writes them back
  2. Auto-generates STACK_DIR and UUID API keys into generated.env
  3. Writes a merged .env.docker for Compose Manager Plus
  4. Writes all app config files to configs/ so no setup wizard is needed
  5. Creates the /mnt/user/data/ directory structure

Two env files:
  .env          — what you type (credentials, settings)
  generated.env — what the script writes (API keys, paths, tokens)

Safe to re-run — skips prompts for values already set, won't overwrite
existing API keys, and mkdir -p is idempotent.

Uses only stdlib — no pip dependencies.
"""

import os
import sys
import json
import uuid
import subprocess
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths — derived from script location, not hardcoded
# ---------------------------------------------------------------------------
STACK_DIR      = Path(__file__).resolve().parent.parent   # homeserver/
ENV_FILE       = STACK_DIR / ".env"           # user-edited credentials
GENERATED_FILE = STACK_DIR / "generated.env"  # machine-written, gitignored
DOCKER_ENV     = STACK_DIR / ".env.docker"    # merged, for Compose Manager Plus
CONFIGS        = STACK_DIR / "configs"

# ---------------------------------------------------------------------------
# .env loader / writer
# ---------------------------------------------------------------------------
def _parse_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                val = val.split("#")[0].strip()
                env[key.strip()] = val
    return env

def load_env(*paths: Path) -> dict:
    """Load and merge one or more env files. Later files win on conflict."""
    env = {}
    for path in paths:
        if not path.exists():
            continue
        env.update(_parse_env_file(path))
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found.")
        print(f"  cp {ENV_FILE.parent}/.env.example {ENV_FILE}")
        sys.exit(1)
    return env

def write_back_to_env(path: Path, updates: dict):
    """Update existing keys in path in place; append any not found."""
    lines = path.read_text().splitlines(keepends=True) if path.exists() else []
    found = set()
    out = []
    for line in lines:
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.partition("=")[0].strip()
            if key in updates:
                out.append(f"{key}={updates[key]}\n")
                found.add(key)
                continue
        out.append(line)
    for key, val in updates.items():
        if key not in found:
            out.append(f"{key}={val}\n")
    path.write_text("".join(out))
    path.chmod(0o600)

def write_generated(updates: dict):
    """Write (or update) generated.env with machine-generated values."""
    existing = _parse_env_file(GENERATED_FILE) if GENERATED_FILE.exists() else {}
    existing.update(updates)
    lines = ["# Auto-generated by scripts — do not edit by hand\n"]
    for k, v in existing.items():
        lines.append(f"{k}={v}\n")
    GENERATED_FILE.write_text("".join(lines))
    GENERATED_FILE.chmod(0o600)

def write_merged_docker_env():
    """Write .env.docker = .env + generated.env merged, for Compose Manager Plus."""
    merged = {}
    for path in (ENV_FILE, GENERATED_FILE):
        if path.exists():
            merged.update(_parse_env_file(path))
    lines = ["# Merged env for Compose Manager Plus — auto-generated, do not edit\n"]
    for k, v in merged.items():
        lines.append(f"{k}={v}\n")
    DOCKER_ENV.write_text("".join(lines))
    DOCKER_ENV.chmod(0o600)

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------
def ask(label: str, default: str = "", hint: str = "") -> str:
    """Prompt until a non-empty value is entered. Returns default if provided and input is blank."""
    if hint:
        print(f"    {hint}")
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {label}{suffix}: ").strip()
        if val:
            return val
        if default:
            return default
        print("    Required.")

def prompt_for_missing(env: dict) -> dict:
    """
    Prompt for any missing required values. Returns a dict of new values
    collected — caller is responsible for merging into env and writing back.
    """
    updates = {}

    def get_or_ask(key: str, label: str, default: str = "", hint: str = "") -> str:
        val = env.get(key, "").strip()
        if val:
            return val
        val = ask(label, default=default, hint=hint)
        updates[key] = val
        return val

    missing = [
        k for k in [
            "TZ", "DOMAIN", "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
            "USENET_HOST", "USENET_USER", "USENET_PASS",
            "NZBGEEK_API_KEY", "NZBPLANET_API_KEY", "CLOUDFLARE_TUNNEL_TOKEN",
        ]
        if not env.get(k, "").strip()
    ]

    if not missing:
        return updates  # nothing to ask

    print("\nSome required values are missing from .env. Let's fill them in.\n")

    # System
    if "TZ" in missing:
        print("--- System ---")
        get_or_ask("TZ", "Timezone", hint="e.g. America/New_York, America/Los_Angeles, Europe/London")

    # Network / Plex
    net_missing = [k for k in ["DOMAIN", "PLEX_LAN_IP", "PLEX_LAN_SUBNET"] if k in missing]
    if net_missing:
        print("\n--- Network ---")
        if "DOMAIN" in missing:
            get_or_ask("DOMAIN", "Domain", hint="e.g. smithmedia.net (registered via Cloudflare Registrar)")
        if "PLEX_LAN_IP" in missing:
            get_or_ask("PLEX_LAN_IP", "Server LAN IP", hint="shown in Unraid UI top-right corner, e.g. 192.168.1.50")
        if "PLEX_LAN_SUBNET" in missing:
            get_or_ask("PLEX_LAN_SUBNET", "LAN subnet (CIDR)", hint="e.g. 192.168.1.0/24  — run: ip route | grep default")

    # Usenet
    usenet_missing = [k for k in ["USENET_HOST", "USENET_USER", "USENET_PASS"] if k in missing]
    if usenet_missing:
        print("\n--- Usenet (primary provider) ---")
        get_or_ask("USENET_HOST", "Provider hostname", hint="e.g. news.newshosting.com")
        get_or_ask("USENET_USER", "Username")
        get_or_ask("USENET_PASS", "Password")
        if not env.get("USENET_CONNECTIONS", "").strip():
            val = ask("Max connections", default="20", hint="check your plan — Newshosting Unlimited = 30+")
            if val != "20":
                updates["USENET_CONNECTIONS"] = val

    # Optional fill server
    fill_keys = ["USENET_FILL_HOST", "USENET_FILL_USER", "USENET_FILL_PASS"]
    has_fill = any(env.get(k, "").strip() for k in fill_keys)
    if not has_fill:
        ans = input("\n  Add a fill/backup Usenet server (different backbone)? [y/N]: ").strip().lower()
        if ans == "y":
            updates["USENET_FILL_HOST"] = ask("Fill server hostname")
            updates["USENET_FILL_USER"] = ask("Fill server username")
            updates["USENET_FILL_PASS"] = ask("Fill server password")

    # Indexers
    idx_missing = [k for k in ["NZBGEEK_API_KEY", "NZBPLANET_API_KEY"] if k in missing]
    if idx_missing:
        print("\n--- Indexers ---")
        if "NZBGEEK_API_KEY" in missing:
            get_or_ask("NZBGEEK_API_KEY", "NZBGeek API key", hint="nzbgeek.info → My Profile → API Key")
        if "NZBPLANET_API_KEY" in missing:
            get_or_ask("NZBPLANET_API_KEY", "NZBPlanet API key", hint="nzbplanet.net → My Account → API Key")

    # Cloudflare
    if "CLOUDFLARE_TUNNEL_TOKEN" in missing:
        print("\n--- Cloudflare ---")
        get_or_ask(
            "CLOUDFLARE_TUNNEL_TOKEN", "Tunnel token",
            hint="Zero Trust → Networks → Tunnels → your tunnel → Configure → Token"
        )

    # Plex server name (optional, has default)
    if not env.get("PLEX_SERVER_NAME", "").strip():
        print("\n--- Plex ---")
        val = ask("Plex server name (shown in clients)", default="Home Media Server")
        if val != "Home Media Server":
            updates["PLEX_SERVER_NAME"] = val

    return updates


# ---------------------------------------------------------------------------
# Config writers
# ---------------------------------------------------------------------------
def _write_secret(path: Path, content: str):
    """Write a config file that contains credentials or API keys. Mode 0600
    so only the owner (nobody on Unraid, after chown) can read it."""
    path.write_text(content)
    path.chmod(0o600)

def write_sabnzbd(env: dict):
    dest = CONFIGS / "sabnzbd"
    dest.mkdir(parents=True, exist_ok=True)

    api_key  = env["SABNZBD_API_KEY"]
    domain   = env["DOMAIN"]
    host     = env["USENET_HOST"]
    port     = env.get("USENET_PORT", "563")
    ssl      = env.get("USENET_SSL", "1")
    user     = env["USENET_USER"]
    password = env["USENET_PASS"]
    conns    = env.get("USENET_CONNECTIONS", "20")

    fill_host  = env.get("USENET_FILL_HOST", "")
    fill_user  = env.get("USENET_FILL_USER", "")
    fill_pass  = env.get("USENET_FILL_PASS", "")
    fill_conns = env.get("USENET_FILL_CONNECTIONS", "10")

    fill_block = ""
    if fill_host and fill_user and fill_pass:
        fill_block = f"""
    [[server2]]
    displayname = Fill Server
    host = {fill_host}
    port = 563
    ssl = 1
    ssl_verify = 2
    username = {fill_user}
    password = {fill_pass}
    connections = {fill_conns}
    priority = 1
    retention = 0
    timeout = 60
    required = 0
    optional = 1
    enabled = 1"""

    content = f"""[misc]
host = 0.0.0.0
port = 8080
url_base = /sabnzbd
# host_whitelist blocks requests from hostnames not listed here.
# This WILL break access through the Cloudflare tunnel unless your
# manage.yourdomain.com is present. Add more comma-separated entries as needed.
host_whitelist = localhost,sabnzbd,mediaserver.local,manage.{domain}
api_key = {api_key}
nzo_ids = {api_key}
wizard_step = 10
language = en
cherryhost = 0.0.0.0
cherryport = 8080
download_dir = /data/usenet/incomplete
complete_dir = /data/usenet/complete
log_dir = /config/logs
admin_dir = /config/admin
# 0 = unlimited. Set to your connection speed in KB/s to cap usage.
# 100Mbps=12500  250Mbps=31250  500Mbps=62500  1Gbps=125000
bandwidth_max = 0
bandwidth_perc = 100
direct_unpack = 1
pause_on_post_processing = 0
enable_par_cleanup = 1
cleanup_list = .nfo, .sfv, .jpg, .png, .nzb
fail_on_fail = 0
history_retention = 30
history_limit = 200
dupl_priority = -100
check_new_rel = 0
enable_broadcast = 0
keep_awake = 1
send_group = 0

[notifications]
ntf_enable = 0

[servers]

    [[server1]]
    displayname = Primary Provider
    host = {host}
    port = {port}
    ssl = {ssl}
    ssl_verify = 2
    username = {user}
    password = {password}
    connections = {conns}
    priority = 0
    retention = 0
    timeout = 60
    required = 0
    optional = 0
    enabled = 1
{fill_block}

[categories]

    [[movies]]
    name = movies
    dir = movies
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[tv]]
    name = tv
    dir = tv
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[music]]
    name = music
    dir = music
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[*]]
    name = *
    dir =
    pp = 3
    script = None
    priority = -100
    req_completion_rate = 100.0
    newzbin =
"""
    _write_secret(dest / "sabnzbd.ini", content)
    print("  ✓ configs/sabnzbd/sabnzbd.ini")

def write_arr_config(name: str, port: int, api_key: str, url_base: str):
    dest = CONFIGS / name
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""<Config>
  <BindAddress>*</BindAddress>
  <Port>{port}</Port>
  <SslPort>{port + 1000}</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>False</LaunchBrowser>
  <ApiKey>{api_key}</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
  <Branch>main</Branch>
  <LogLevel>info</LogLevel>
  <UrlBase>{url_base}</UrlBase>
  <UpdateMechanism>Docker</UpdateMechanism>
</Config>
"""
    _write_secret(dest / "config.xml", content)
    print(f"  ✓ configs/{name}/config.xml")

def write_overseerr(env: dict):
    dest = CONFIGS / "overseerr"
    dest.mkdir(parents=True, exist_ok=True)

    domain = env["DOMAIN"]
    lan_ip = env["PLEX_LAN_IP"]

    settings = {
        "apiKey": uuid.uuid4().hex,
        "main": {
            "apiKey": uuid.uuid4().hex,
            "applicationTitle": "Media Requests",
            "applicationUrl": f"https://request.{domain}",
            "trustProxy": True,
            "hideAvailable": False,
            "localLogin": True,
            "newPlexLogin": True,
            "defaultPermissions": 32,
            "defaultQuotas": {
                "movie": {"quotaLimit": 0, "quotaDays": 7},
                "tv":    {"quotaLimit": 0, "quotaDays": 7}
            },
            "partialRequestsEnabled": True,
            "locale": "en"
        },
        "plex": {
            "name": env.get("PLEX_SERVER_NAME", "Home Media Server"),
            "ip": lan_ip,
            "port": 32400,
            "useSsl": False,
            "libraries": []
        },
        "tautulli": None,
        "radarr": [],
        "sonarr": [],
        "public": {"initialized": False},
        "notifications": {
            "agents": {
                "email":      {"enabled": False, "types": 0, "options": {}},
                "discord":    {"enabled": False, "types": 0, "options": {}},
                "slack":      {"enabled": False, "types": 0, "options": {}},
                "telegram":   {"enabled": False, "types": 0, "options": {}},
                "pushbullet": {"enabled": False, "types": 0, "options": {}},
                "pushover":   {"enabled": False, "types": 0, "options": {}},
                "lunasea":    {"enabled": False, "types": 0, "options": {}},
                "gotify":     {"enabled": False, "types": 0, "options": {}},
                "ntfy":       {"enabled": False, "types": 0, "options": {}},
                "webpush":    {"enabled": False, "types": 0, "options": {}}
            }
        },
        "jobs": {}
    }

    _write_secret(dest / "settings.json", json.dumps(settings, indent=2))
    print("  ✓ configs/overseerr/settings.json")

def write_bazarr(env: dict):
    dest = CONFIGS / "bazarr"
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""[general]
ip = 0.0.0.0
port = 6767
base_url = /bazarr
launch_browser = False
update_upgrade = False
timezone = {env.get("TZ", "UTC")}

[auth]
type = None

[sonarr]
ip = sonarr
port = 8989
base_url = /sonarr
ssl = False
apikey = {env["SONARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[radarr]
ip = radarr
port = 7878
base_url = /radarr
ssl = False
apikey = {env["RADARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[subliminal]
hearing_impaired_subtitles = False
single_language = False

[opensubtitles]
enabled = False
username =
password =

[languages]
single = False
subtitles_languages = ['en']
enabled_codecs = ['utf-8']
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/bazarr/config.ini")

def write_tautulli(env: dict):
    """Pre-seed Tautulli config.ini with HTTP settings + API key.

    PMS connection (server token, identifier) is left to Tautulli's first-run
    wizard — it's a ~30-second flow and needs PLEX_TOKEN which may not be
    captured until bootstrap.py runs interactively.
    """
    dest = CONFIGS / "tautulli"
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""[General]
api_key = {env["TAUTULLI_API_KEY"]}
http_host = 0.0.0.0
http_port = 8181
http_root = /
launch_browser = 0
check_github = 0
enable_plex_update_notify = 0

[Monitoring]
refresh_libraries_on_startup = 0
refresh_users_on_startup = 0
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/tautulli/config.ini")

# ---------------------------------------------------------------------------
# Data directory creation
# ---------------------------------------------------------------------------
def create_data_dirs():
    dirs = [
        Path("/mnt/user/data/usenet/incomplete"),
        Path("/mnt/user/data/usenet/complete/movies"),
        Path("/mnt/user/data/usenet/complete/tv"),
        Path("/mnt/user/data/usenet/complete/music"),
        Path("/mnt/user/data/media/movies"),
        Path("/mnt/user/data/media/tv"),
        Path("/mnt/user/data/media/music"),
        Path("/mnt/user/appdata/plex-transcode"),
    ]
    created = [d for d in dirs if not d.exists()]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    if created:
        subprocess.run(["chown", "-R", "nobody:users", "/mnt/user/data/"], check=False)
        for d in created:
            print(f"  ✓ created {d}")
    else:
        print("  ✓ data directories already exist")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print(f"Stack directory: {STACK_DIR}\n")

    # Load both files — generated.env may not exist yet on first run
    env = load_env(ENV_FILE, GENERATED_FILE)

    # Step 1: Interactively collect any missing credentials → .env
    new_values = prompt_for_missing(env)
    if new_values:
        env.update(new_values)
        write_back_to_env(ENV_FILE, new_values)
        print("\n  .env updated.\n")

    # Step 2: Generate any missing machine values → generated.env
    api_key_fields = [
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY", "TAUTULLI_API_KEY",
    ]
    auto = {}
    if not env.get("STACK_DIR", "").strip():
        auto["STACK_DIR"] = str(STACK_DIR)
    for k in api_key_fields:
        if not env.get(k, "").strip():
            auto[k] = uuid.uuid4().hex
    if auto:
        env.update(auto)
        write_generated(auto)
        print("Generated and saved to generated.env:")
        for k in auto:
            print(f"  {k}")
        print()

    # Step 3: Write merged .env.docker for Compose Manager Plus
    write_merged_docker_env()

    # Step 4: Final validation — everything required must now be set.
    required = [
        "TZ", "DOMAIN", "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY",
        "USENET_HOST", "USENET_USER", "USENET_PASS",
        "NZBGEEK_API_KEY", "NZBPLANET_API_KEY",
        "CLOUDFLARE_TUNNEL_TOKEN",
    ]
    missing = [k for k in required if not env.get(k, "").strip()]
    if missing:
        print("ERROR: These required values are still not set:")
        for k in missing:
            print(f"  {k}")
        sys.exit(1)

    # Step 5: Write app configs.
    print("\nWriting config files...")
    write_sabnzbd(env)
    write_arr_config("radarr",   7878, env["RADARR_API_KEY"],  "/radarr")
    write_arr_config("sonarr",   8989, env["SONARR_API_KEY"],  "/sonarr")
    write_arr_config("lidarr",   8686, env["LIDARR_API_KEY"],  "/lidarr")
    write_arr_config("prowlarr", 9696, env["PROWLARR_API_KEY"],"/prowlarr")
    write_overseerr(env)
    write_bazarr(env)
    write_tautulli(env)

    # Step 6: Create data directories.
    print("\nCreating data directories...")
    create_data_dirs()

    print(f"""
Done.

Next steps:
  1. Start the stack:
       docker compose --env-file .env --env-file generated.env up -d
     Or use Compose Manager Plus with .env.docker as the env file.
  2. Wait ~60s for containers to initialise.
  3. python3 scripts/bootstrap.py
""")

if __name__ == "__main__":
    main()
