#!/usr/bin/env python3
"""
generate-configs.py
===================
Interactive setup script. Run once before starting the stack.

  cd /mnt/user/appdata/homeserver/homeserver
  python3 scripts/generate-configs.py

What it does:
  1. Prompts for any credentials not yet in .env, writes them back
  2. Auto-generates STACK_DIR, UUID API keys and the Nextcloud passwords
     into generated.env
  3. Writes a merged .env.docker (convenience single-file env for `docker compose --env-file`)
  4. Writes all app config files to configs/ so no setup wizard is needed
  5. Creates the /mnt/user/data/ directory structure

Two env files:
  .env          — what you type (credentials, settings)
  generated.env — what the script writes (API keys, paths, tokens)

Safe to re-run — skips prompts for values already set, won't overwrite
existing API keys, and mkdir -p is idempotent.

Uses only stdlib — no pip dependencies.
"""

import argparse
import ipaddress
import json
import secrets
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Callable, Optional

# ---------------------------------------------------------------------------
# Paths — derived from script location, not hardcoded
# ---------------------------------------------------------------------------
STACK_DIR: Path      = Path(__file__).resolve().parent.parent   # homeserver/
ENV_FILE: Path       = STACK_DIR / ".env"           # user-edited credentials
GENERATED_FILE: Path = STACK_DIR / "generated.env"  # machine-written, gitignored
DOCKER_ENV: Path     = STACK_DIR / ".env.docker"    # merged, single-file env
CONFIGS: Path        = STACK_DIR / "configs"

# ---------------------------------------------------------------------------
# .env loader / writer
# ---------------------------------------------------------------------------
def _parse_env_file(path: Path) -> dict:
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                val = val.split("#")[0].strip()
                env[key.strip()] = val
    return env

def load_env(*paths: Path) -> dict:
    """Load and merge one or more env files. Later files win on conflict."""
    env = {}
    for path in paths:
        if not path.exists():
            continue
        env.update(_parse_env_file(path))
    if not ENV_FILE.exists():
        print(f"ERROR: {ENV_FILE} not found.")
        print(f"  cp {ENV_FILE.parent}/.env.example {ENV_FILE}")
        sys.exit(1)
    return env

def write_back_to_env(path: Path, updates: dict):
    """Update existing keys in path in place; append any not found."""
    lines = path.read_text().splitlines(keepends=True) if path.exists() else []
    found = set()
    out = []
    for line in lines:
        stripped = line.strip()
        if "=" in stripped and not stripped.startswith("#"):
            key = stripped.partition("=")[0].strip()
            if key in updates:
                out.append(f"{key}={updates[key]}\n")
                found.add(key)
                continue
        out.append(line)
    for key, val in updates.items():
        if key not in found:
            out.append(f"{key}={val}\n")
    path.write_text("".join(out))
    path.chmod(0o600)

def write_generated(updates: dict):
    """Write (or update) generated.env with machine-generated values."""
    existing = _parse_env_file(GENERATED_FILE) if GENERATED_FILE.exists() else {}
    existing.update(updates)
    lines = ["# Auto-generated by scripts — do not edit by hand\n"]
    for k, v in existing.items():
        lines.append(f"{k}={v}\n")
    GENERATED_FILE.write_text("".join(lines))
    GENERATED_FILE.chmod(0o600)

def write_merged_docker_env():
    """Write .env.docker = .env + generated.env merged — convenience for tooling that takes a single --env-file."""
    merged = {}
    for path in (ENV_FILE, GENERATED_FILE):
        if path.exists():
            merged.update(_parse_env_file(path))
    lines = ["# Merged env — auto-generated, do not edit\n"]
    for k, v in merged.items():
        lines.append(f"{k}={v}\n")
    DOCKER_ENV.write_text("".join(lines))
    DOCKER_ENV.chmod(0o600)

# ---------------------------------------------------------------------------
# Input validators
# Each returns the validated value, or raises ValueError with a user-facing
# message. ask() catches the error and reprompts.
# ---------------------------------------------------------------------------
ZONEINFO = Path("/usr/share/zoneinfo")

def validate_tz(val: str) -> str:
    # /usr/share/zoneinfo exists on every Unraid host and every modern Linux.
    # On platforms where it doesn't (e.g. running this script on macOS for
    # testing), skip validation rather than rejecting every timezone.
    if ZONEINFO.exists() and not (ZONEINFO / val).is_file():
        raise ValueError(f"not a valid timezone (no {ZONEINFO}/{val})")
    return val

def validate_ip(val: str) -> str:
    try:
        ipaddress.ip_address(val)
    except ValueError as e:
        raise ValueError(f"not a valid IP address: {e}") from e
    return val

def validate_cidr(val: str) -> str:
    try:
        ipaddress.ip_network(val, strict=False)
    except ValueError as e:
        raise ValueError(f"not a valid CIDR: {e}") from e
    return val

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------
def ask(label: str, default: str = "", hint: str = "",
        validator: Optional[Callable[[str], str]] = None) -> str:
    """Prompt until a non-empty value is entered and (optionally) validates.
    Returns default if provided and input is blank.
    """
    if hint:
        print(f"    {hint}")
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {label}{suffix}: ").strip()
        if not val and default:
            val = default
        if not val:
            print("    Required.")
            continue
        if validator is not None:
            try:
                return validator(val)
            except ValueError as e:
                print(f"    Invalid: {e}")
                continue
        return val

def prompt_for_missing(env: dict) -> dict:
    """
    Prompt for any missing required values. Returns a dict of new values
    collected — caller is responsible for merging into env and writing back.
    """
    updates = {}

    def get_or_ask(key: str, label: str, default: str = "", hint: str = "",
                   validator: Optional[Callable[[str], str]] = None) -> str:
        val = env.get(key, "").strip()
        if val:
            return val
        val = ask(label, default=default, hint=hint, validator=validator)
        updates[key] = val
        return val

    missing = [
        k for k in [
            "TZ", "TAILNET_NAME",
            "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
            "VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY",
            "USENET_HOST", "USENET_USER", "USENET_PASS",
            "NZBGEEK_API_KEY", "NZBPLANET_API_KEY",
        ]
        if not env.get(k, "").strip()
    ]

    if not missing:
        return updates  # nothing to ask

    print("\nSome required values are missing from .env. Let's fill them in.\n")

    # System
    if "TZ" in missing:
        print("--- System ---")
        get_or_ask("TZ", "Timezone",
                   default="America/Los_Angeles",
                   hint="e.g. America/New_York, America/Los_Angeles, Europe/London",
                   validator=validate_tz)

    if "TAILNET_NAME" in missing:
        print("--- Tailscale ---")
        # Required, not optional: write_sabnzbd() puts this in SAB's
        # host_whitelist. SAB returns 403 for any Host header it does not know,
        # and `tailscale serve` passes the original Host through — so a blank
        # value produces a SAB that works perfectly on loopback and 403s from
        # every tailnet device. Prompting is the only thing that stops that
        # being discovered days later.
        get_or_ask("TAILNET_NAME", "Tailnet MagicDNS domain",
                   hint="`tailscale status` or admin console -> DNS, "
                        "no leading dot (e.g. tail1a2b3.ts.net)")

    # Network / Plex
    net_missing = [k for k in ["PLEX_LAN_IP", "PLEX_LAN_SUBNET"] if k in missing]
    if net_missing:
        print("\n--- Network ---")
        if "PLEX_LAN_IP" in missing:
            get_or_ask("PLEX_LAN_IP", "Server LAN IP",
                       hint="shown in Unraid UI top-right corner, e.g. 192.168.1.50",
                       validator=validate_ip)
        if "PLEX_LAN_SUBNET" in missing:
            get_or_ask("PLEX_LAN_SUBNET", "LAN subnet (CIDR)",
                       hint="e.g. 192.168.1.0/24  — run: ip route | grep default",
                       validator=validate_cidr)

    # Mullvad WireGuard — for Gluetun outbound VPN on SAB + Prowlarr
    vpn_missing = [k for k in ["VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY"] if k in missing]
    if vpn_missing:
        print("\n--- Mullvad WireGuard (Gluetun outbound VPN) ---")
        print("  Generate a config at mullvad.net/account → WireGuard configuration.")
        if "VPN_PRIVATE_KEY" in missing:
            get_or_ask("VPN_PRIVATE_KEY", "WireGuard private key",
                       hint="from [Interface] PrivateKey = ... in the downloaded .conf")
        if "VPN_ADDRESS" in missing:
            get_or_ask("VPN_ADDRESS", "WireGuard address",
                       hint="from [Interface] Address = ... (comma-separated v4,v6)")
        if "VPN_CITY" in missing:
            get_or_ask("VPN_CITY", "Exit city",
                       default="Amsterdam",
                       hint="pick one near your Usenet provider for lowest latency")

    # Usenet
    usenet_missing = [k for k in ["USENET_HOST", "USENET_USER", "USENET_PASS"] if k in missing]
    if usenet_missing:
        print("\n--- Usenet (primary provider) ---")
        get_or_ask("USENET_HOST", "Provider hostname", hint="e.g. news.newshosting.com")
        get_or_ask("USENET_USER", "Username")
        get_or_ask("USENET_PASS", "Password")
        if not env.get("USENET_CONNECTIONS", "").strip():
            val = ask("Max connections", default="20", hint="check your plan — Newshosting Unlimited = 30+")
            if val != "20":
                updates["USENET_CONNECTIONS"] = val

    # Optional fill server
    fill_keys = ["USENET_FILL_HOST", "USENET_FILL_USER", "USENET_FILL_PASS"]
    has_fill = any(env.get(k, "").strip() for k in fill_keys)
    if not has_fill:
        ans = input("\n  Add a fill/backup Usenet server (different backbone)? [y/N]: ").strip().lower()
        if ans == "y":
            updates["USENET_FILL_HOST"] = ask("Fill server hostname")
            updates["USENET_FILL_USER"] = ask("Fill server username")
            updates["USENET_FILL_PASS"] = ask("Fill server password")

    # Indexers
    idx_missing = [k for k in ["NZBGEEK_API_KEY", "NZBPLANET_API_KEY"] if k in missing]
    if idx_missing:
        print("\n--- Indexers ---")
        if "NZBGEEK_API_KEY" in missing:
            get_or_ask("NZBGEEK_API_KEY", "NZBGeek API key", hint="nzbgeek.info → My Profile → API Key")
        if "NZBPLANET_API_KEY" in missing:
            get_or_ask("NZBPLANET_API_KEY", "NZBPlanet API key", hint="nzbplanet.net → My Account → API Key")

    # Plex server name (optional, has default)
    if not env.get("PLEX_SERVER_NAME", "").strip():
        print("\n--- Plex ---")
        val = ask("Plex server name (shown in clients)", default="Home Media Server")
        if val != "Home Media Server":
            updates["PLEX_SERVER_NAME"] = val

    return updates


# ---------------------------------------------------------------------------
# Config writers
# ---------------------------------------------------------------------------
_PRESERVE_USER_EDITS = True
_PENDING_NEW_FILES: list[Path] = []

def _lock_down(path: Path) -> None:
    """Mode 0600 + chown nobody:users (99:100 on Unraid).

    Containers run as PUID/PGID = 99/100. These files are bind-mounted into
    /config; if they stay root-owned, the container gets 'Permission denied'
    on open. Hotio's *arr images and SABnzbd both fail-fast on this and
    crash-loop. chown is best-effort so the script still works on dev
    machines without a 'users' group at GID 100.
    """
    path.chmod(0o600)
    subprocess.run(["chown", "nobody:users", str(path)], check=False)

def _write_secret(path: Path, content: str) -> None:
    """Write a config file that contains credentials or API keys. Mode 0600
    + owned by nobody:users so the bind-mounting container can read it.

    If the target file already exists and its content differs from what we
    want to write, the new template is written alongside as <path>.new and
    the existing file is left untouched. This preserves user customizations
    made through a service's own UI (e.g. additional Radarr custom formats)
    on re-runs of generate-configs.py. Matches the Debian/Unraid convention
    for handling package-owned config files that may have been edited. main()
    prints a summary at the end for every `.new` file produced, so they're
    hard to miss.

    The .new-on-conflict behavior can be disabled with --force-overwrite.
    """
    if path.exists() and _PRESERVE_USER_EDITS:
        if path.read_text() == content:
            _lock_down(path)
            return
        new_path = path.with_suffix(path.suffix + ".new")
        new_path.write_text(content)
        _lock_down(new_path)
        _PENDING_NEW_FILES.append(path)
        print(f"    ! existing file preserved; new template at {new_path.name}")
        return
    path.write_text(content)
    _lock_down(path)

def write_sabnzbd(env: dict):
    dest = CONFIGS / "sabnzbd"
    dest.mkdir(parents=True, exist_ok=True)

    api_key  = env["SABNZBD_API_KEY"]

    # Tailscale Services pass the original Host header through, so SAB's
    # host_whitelist has to contain the Service FQDN or the UI 403s from the
    # tailnet while working on loopback. Both the bare and fully-qualified
    # MagicDNS forms are listed because MagicDNS puts the tailnet domain in the
    # search path on most platforms, so browsers reach it either way.
    tailnet = env.get("TAILNET_NAME", "").strip().lstrip(".")
    sab_serve_hosts = f",sab,sab.{tailnet}" if tailnet else ""

    host     = env["USENET_HOST"]
    port     = env.get("USENET_PORT", "563")
    ssl      = env.get("USENET_SSL", "1")
    user     = env["USENET_USER"]
    password = env["USENET_PASS"]
    conns    = env.get("USENET_CONNECTIONS", "20")

    fill_host  = env.get("USENET_FILL_HOST", "")
    fill_user  = env.get("USENET_FILL_USER", "")
    fill_pass  = env.get("USENET_FILL_PASS", "")
    fill_conns = env.get("USENET_FILL_CONNECTIONS", "10")

    fill_block = ""
    if fill_host and fill_user and fill_pass:
        fill_block = f"""
    [[server2]]
    displayname = Fill Server
    host = {fill_host}
    port = 563
    ssl = 1
    ssl_verify = 2
    username = {fill_user}
    password = {fill_pass}
    connections = {fill_conns}
    priority = 1
    retention = 0
    timeout = 60
    required = 0
    optional = 1
    enabled = 1"""

    content = f"""[misc]
host = 0.0.0.0
port = 8080
url_base =
# host_whitelist blocks requests from hostnames not listed here: SAB returns
# 403 for any request whose Host header isn't on the list. `tailscale serve`
# passes the original Host through, so the Service FQDN must be present or the
# SAB UI is a hard 403 from the tailnet while working fine on loopback — which
# looks like an ingress bug and isn't one.
#
# TAILNET_NAME comes from .env (e.g. tail1a2b3.ts.net). If it's blank the
# FQDN entries are simply omitted and SAB is reachable on loopback only.
host_whitelist = localhost,sabnzbd,gluetun,mediaserver.local{sab_serve_hosts}
api_key = {api_key}
nzo_ids = {api_key}
wizard_step = 10
language = en
cherryhost = 0.0.0.0
cherryport = 8080
download_dir = /incomplete
complete_dir = /data/usenet/complete
log_dir = /config/logs
admin_dir = /config/admin
# 0 = unlimited. Set to your connection speed in KB/s to cap usage.
# 100Mbps=12500  250Mbps=31250  500Mbps=62500  1Gbps=125000
bandwidth_max = 0
bandwidth_perc = 100
direct_unpack = 1
pause_on_post_processing = 0
enable_par_cleanup = 1
cleanup_list = .nfo, .sfv, .jpg, .png, .nzb
fail_on_fail = 0
# History retention bounds the HISTORY LIST only. It does not reclaim disk:
# upstream never supported delete-files for successfully completed jobs,
# because sorting rules and user scripts make the final location unknowable
# to SAB. Deleting the files is the *arr's job, via removeCompletedDownloads
# in bootstrap.py — do not look here for that.
#
# Verified against a running SABnzbd 4.x: it maintains both
# `history_retention = ""` and the `history_retention_option` /
# `history_retention_number` pair, and the option is what governs. Default is
# "all", which is why an untouched instance keeps every job forever.
#
# Whichever key SAB reads, the default when nothing is set is "all": keep
# every completed job forever. That is what produced 127 retained job folders
# and 324 GB on the live box, including failed unpacks and five copies of the
# same episode from repeated re-grabs.
#
# "days" + 14 keeps a two-week window: long enough to notice and re-import a
# job that went wrong, short enough that the buffer stays bounded.
#
# NOTE: this file is only written on a fresh install. generate-configs.py
# preserves an existing sabnzbd.ini and writes sabnzbd.ini.new alongside it,
# so changing this does NOT alter a running box — set it via SAB's API or UI
# there, or reconcile the .new file deliberately.
history_retention_option = days
history_retention_number = 14
history_limit = 200
dupl_priority = -100
check_new_rel = 0
enable_broadcast = 0
keep_awake = 1
send_group = 0

[notifications]
ntf_enable = 0

[servers]

    [[server1]]
    displayname = Primary Provider
    host = {host}
    port = {port}
    ssl = {ssl}
    ssl_verify = 2
    username = {user}
    password = {password}
    connections = {conns}
    priority = 0
    retention = 0
    timeout = 60
    required = 0
    optional = 0
    enabled = 1
{fill_block}

[categories]

    [[movies]]
    name = movies
    dir = movies
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[tv]]
    name = tv
    dir = tv
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[music]]
    name = music
    dir = music
    pp = 3
    script = None
    req_completion_rate = 100.0
    priority = -100
    newzbin =

    [[*]]
    name = *
    dir =
    pp = 3
    script = None
    priority = -100
    req_completion_rate = 100.0
    newzbin =
"""
    _write_secret(dest / "sabnzbd.ini", content)
    print("  ✓ configs/sabnzbd/sabnzbd.ini")

def write_arr_config(name: str, port: int, api_key: str):
    dest = CONFIGS / name
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""<Config>
  <BindAddress>*</BindAddress>
  <Port>{port}</Port>
  <SslPort>{port + 1000}</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>False</LaunchBrowser>
  <ApiKey>{api_key}</ApiKey>
  <!-- The whole stack is admin-only and reachable only via Tailscale (the
       Unraid host enforces that — no public listener for these ports). The
       *arrs sit behind that perimeter, so internal auth would only force
       another credential prompt on every UI visit. The new-style 'None'
       option is still honored when set via config.xml on startup; it's only
       hidden from the UI dropdown to discourage exposing arrs to the open
       internet. AuthenticationRequired is ignored when method is None. -->
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
  <Branch>main</Branch>
  <LogLevel>info</LogLevel>
  <!-- UrlBase empty so each *arr serves at root. tailscale serve fronts them
       at https://<name>.<tailnet>.ts.net/ without a path prefix. -->
  <UrlBase></UrlBase>
  <UpdateMechanism>Docker</UpdateMechanism>
</Config>
"""
    _write_secret(dest / "config.xml", content)
    print(f"  ✓ configs/{name}/config.xml")

def ensure_seerr_appdata():
    """Create /mnt/user/appdata/seerr as nobody:users so the container (which
    runs as 99:100 via the `user:` override in compose) can write its SQLite
    DB on first start. Seerr is configured through its first-run UI flow —
    we don't pre-seed settings.json because the file confuses the settings
    migrator on a fresh install (it tries to record migrations against a
    db.sqlite3 that hasn't been created yet, crash-loops on
    'SQLITE_ERROR: no such table: migrations'). See docs/deployment.md
    for the manual Plex/Radarr/Sonarr wiring step.
    """
    dest = Path("/mnt/user/appdata/seerr")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)
    print(f"  ✓ {dest}/ (Seerr state — configured via web UI)")

def ensure_profilarr_appdata():
    """Create /mnt/user/appdata/profilarr as nobody:users so Profilarr can
    initialise its SQLite DB on first start. Profilarr has no declarative
    config file — all state (subscribed databases, selected profiles, sync
    targets) lives in the SQLite DB and is configured via its web UI after
    first boot. See docs/deployment.md Step 7.
    """
    dest = Path("/mnt/user/appdata/profilarr")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)
    print(f"  ✓ {dest}/ (Profilarr state — configured via web UI)")

def ensure_actual_appdata():
    """Create /mnt/user/appdata/actual as nobody:users before first start.

    actual-server is the one image here that ships no USER directive and takes
    no PUID/PGID — the published image runs as root — so docker-compose.yml
    pins it to 99:100 with an explicit `user:`. That makes this directory
    mandatory: if docker creates it on first mount it lands root-owned, the
    container cannot mkdir /data/server-files, and it restart-loops with an
    EACCES that surfaces as a 502 from its Tailscale Service rather than as
    anything obviously permission-shaped.
    """
    dest = Path("/mnt/user/appdata/actual")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)
    print(f"  ✓ {dest}/ (Actual Budget SQLite — must exist before first start)")

def ensure_chess_coach_appdata():
    """Create /mnt/user/appdata/chess-coach/data as nobody:users.

    ONLY data/ is chowned. The parent also holds the GitHub deploy key and the
    repo checkout, and OpenSSH refuses a private key owned by another user
    ("bad ownership or modes") — a recursive chown of the parent silently
    breaks every future `git pull` for coach updates. data/ is the only path
    bind-mounted into the container.
    """
    dest = Path("/mnt/user/appdata/chess-coach/data")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)
    print(f"  ✓ {dest}/ (chess-coach state — parent left root-owned for the deploy key)")

def ensure_ollama_appdata():
    """Create /mnt/user/appdata/ollama as nobody:users for the model store.

    Ollama runs as 99:100 (`user:` override in compose) with HOME=/ollama, so
    this directory has to exist and be writable before first start or the
    engine can't create its model store.

    Deliberately NOT covered by the weekly Appdata Backup — see
    docs/deployment.md. Model blobs are multi-GB and re-pullable in minutes.
    """
    dest = Path("/mnt/user/appdata/ollama")
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["chown", "-R", "nobody:users", str(dest)], check=False)
    print(f"  ✓ {dest}/ (Ollama models — exclude from Appdata Backup)")

def _appdata_is_cache_only() -> Optional[bool]:
    """Is the appdata share shareUseCache=only?

    Returns True/False, or None if the share config can't be read (e.g. this
    is not an Unraid box, or the file has not been written yet).

    This is the guard for the /mnt/cache bind paths used by the Nextcloud
    plane. With cache=only every appdata file lives on the cache pool, so
    /mnt/cache/appdata/X and /mnt/user/appdata/X are the same files reached
    two ways and mover never touches them. Flip the share to `yes` or `prefer`
    and that stops being true — files can then also exist on the array, the
    two paths diverge, and a performance optimisation quietly becomes data
    corruption. Cheap to check, so check it.
    """
    cfg = Path("/boot/config/shares/appdata.cfg")
    if not cfg.exists():
        return None
    for line in cfg.read_text().splitlines():
        if line.strip().startswith("shareUseCache="):
            return line.split("=", 1)[1].strip().strip('"').strip("'") == "only"
    return None


def ensure_nextcloud_appdata():
    """Create the Nextcloud directories, and deliberately do NOT chown them.

    This inverts the pattern used by every ensure_*_appdata() above, so the
    absence of a chown is the point rather than an oversight:

      * seerr / profilarr / ollama / actual / coach are pinned to 99:100 in
        docker-compose.yml because their images ship no USER directive. Their
        bind dirs must be nobody:users BEFORE first start or the container
        cannot write.

      * Nextcloud and Postgres are the opposite case. Both entrypoints start
        as root, chown their own volumes, and drop privileges themselves — to
        www-data (33) and postgres (70). Chowning to nobody:users here would
        be undone on first start at best, and at worst is exactly what Unraid's
        Tools -> New Permissions does to break a working install.

    So: create, and get out of the way. verify-stack.sh asserts the resulting
    uids are 33 and 70 rather than skipping these paths, so damage from a
    later New Permissions run is caught instead of ignored.
    """
    # NOTE: the shareUseCache=only precondition is checked in main()'s
    # validation step, NOT here. Aborting from this function would exit halfway
    # through writing config files — after the *arr config.xml files but before
    # bazarr's and tautulli's — and both of those are single-FILE bind mounts.
    # Docker creates an empty directory where a missing bind-mount file should
    # be, so a half-written run followed by `compose up` breaks two services in
    # a way that is tedious to diagnose. Validation belongs before the first
    # write, which is where every other check in this script lives.
    cache_only = _appdata_is_cache_only()

    # App code + config, and the database. /mnt/cache on purpose — serving one
    # Nextcloud page stats thousands of PHP files, which is the access pattern
    # shfs punishes hardest.
    for d in (Path("/mnt/cache/appdata/nextcloud"),
              Path("/mnt/cache/appdata/nextcloud-db"),
              Path("/mnt/cache/appdata/nextcloud-dump")):
        d.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {d}/ (ownership left to the container — see decisions.md)")

    # User files. On the array via the user share, because they must span it —
    # and because bulk file I/O is the wrong workload to worry about FUSE for.
    data = Path("/mnt/user/nextcloud")
    data.mkdir(parents=True, exist_ok=True)
    print(f"  ✓ {data}/ (Nextcloud user files — NOT covered by Appdata Backup)")

    if cache_only is None:
        print("      note: could not read /boot/config/shares/appdata.cfg to confirm")
        print("      shareUseCache=only. Verify before first start on a real box.")


def write_bazarr(env: dict):
    dest = CONFIGS / "bazarr"
    dest.mkdir(parents=True, exist_ok=True)

    # base_url left empty for both Bazarr's own listener and its sonarr/radarr
    # client URLs — every app in the stack serves at root, and Tailscale
    # Services front them without a path prefix. Keep the keys present (not
    # absent) because
    # Bazarr's loader can fall back to legacy defaults (/sonarr, /radarr) when
    # a key is missing entirely.
    content = f"""[general]
ip = 0.0.0.0
port = 6767
base_url =
launch_browser = False
update_upgrade = False
timezone = {env.get("TZ", "UTC")}

[auth]
type = None

[sonarr]
ip = sonarr
port = 8989
base_url =
ssl = False
apikey = {env["SONARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[radarr]
ip = radarr
port = 7878
base_url =
ssl = False
apikey = {env["RADARR_API_KEY"]}
full_update = Weekly
full_update_day = 6
full_update_hour = 4
enabled = True

[subliminal]
hearing_impaired_subtitles = False
single_language = False

[opensubtitles]
enabled = False
username =
password =

[languages]
single = False
subtitles_languages = ['en']
enabled_codecs = ['utf-8']
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/bazarr/config.ini")

def write_tautulli(env: dict):
    """Pre-seed Tautulli config.ini with HTTP settings + API key.

    PMS connection (machineIdentifier, token, friendlyName) is filled in by
    bootstrap.py once PLEX_TOKEN is in hand and a PlexServer session can
    resolve the identity. That step also sets first_run_complete=1 to skip
    the wizard entirely. Keeping the two stages split here keeps this file
    pure-static and avoids a chicken-and-egg with the Plex token.
    """
    dest = CONFIGS / "tautulli"
    dest.mkdir(parents=True, exist_ok=True)

    content = f"""[General]
api_key = {env["TAUTULLI_API_KEY"]}
http_host = 0.0.0.0
http_port = 8181
http_root = /
launch_browser = 0
check_github = 0
enable_plex_update_notify = 0

[Monitoring]
refresh_libraries_on_startup = 0
refresh_users_on_startup = 0
"""
    _write_secret(dest / "config.ini", content)
    print("  ✓ configs/tautulli/config.ini")

# ---------------------------------------------------------------------------
#

# ---------------------------------------------------------------------------
# Data directory creation
# ---------------------------------------------------------------------------
def create_data_dirs():
    dirs = [
        # Incomplete downloads live on a cache-only share — setup-unraid.sh
        # provisions /boot/config/shares/usenet-incomplete.cfg with
        # shareUseCache=only so mover never migrates these files to the array.
        Path("/mnt/user/usenet-incomplete"),
        Path("/mnt/user/data/usenet/complete/movies"),
        Path("/mnt/user/data/usenet/complete/tv"),
        Path("/mnt/user/data/usenet/complete/music"),
        Path("/mnt/user/data/media/movies"),
        Path("/mnt/user/data/media/tv"),
        Path("/mnt/user/data/media/music"),
        Path("/mnt/user/appdata/plex-transcode"),
    ]
    created = [d for d in dirs if not d.exists()]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    if created:
        subprocess.run(["chown", "-R", "nobody:users", "/mnt/user/data/"], check=False)
        for d in created:
            print(f"  ✓ created {d}")
    else:
        print("  ✓ data directories already exist")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Interactive setup: writes .env + generated.env + per-service configs."
    )
    p.add_argument(
        "--stack-dir", type=Path,
        help="Override the homeserver/ directory (default: inferred from script location)"
    )
    p.add_argument(
        "--force-overwrite", action="store_true",
        help="Overwrite existing config files instead of writing a .new alongside."
    )
    return p.parse_args()


def main() -> None:
    global STACK_DIR, ENV_FILE, GENERATED_FILE, DOCKER_ENV, CONFIGS, _PRESERVE_USER_EDITS
    args = _parse_args()
    if args.stack_dir:
        STACK_DIR = args.stack_dir.resolve()
        ENV_FILE = STACK_DIR / ".env"
        GENERATED_FILE = STACK_DIR / "generated.env"
        DOCKER_ENV = STACK_DIR / ".env.docker"
        CONFIGS = STACK_DIR / "configs"
    _PRESERVE_USER_EDITS = not args.force_overwrite

    print(f"Stack directory: {STACK_DIR}\n")

    # Load both files — generated.env may not exist yet on first run
    env = load_env(ENV_FILE, GENERATED_FILE)

    # Step 1: Interactively collect any missing credentials → .env
    new_values = prompt_for_missing(env)
    if new_values:
        env.update(new_values)
        write_back_to_env(ENV_FILE, new_values)
        print("\n  .env updated.\n")

    # Step 2: Generate any missing machine values → generated.env
    api_key_fields = [
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY", "TAUTULLI_API_KEY",
    ]
    # Passwords, not API keys. token_urlsafe rather than uuid4().hex because
    # one of these (the admin password) gets typed by a human, and because a
    # hex string is a weaker password of the same length. It stays safe for
    # both consumers: the alphabet has no '#' for _parse_env_file's inline
    # comment strip to truncate at, and no '@' or ':' to break Postgres's
    # connection string.
    secret_fields = [
        "NEXTCLOUD_DB_PASSWORD", "NEXTCLOUD_REDIS_PASSWORD",
        "NEXTCLOUD_ADMIN_PASSWORD",
    ]
    auto = {}
    if not env.get("STACK_DIR", "").strip():
        auto["STACK_DIR"] = str(STACK_DIR)
    for k in api_key_fields:
        if not env.get(k, "").strip():
            auto[k] = uuid.uuid4().hex
    for k in secret_fields:
        if not env.get(k, "").strip():
            auto[k] = secrets.token_urlsafe(24)
    if auto:
        env.update(auto)
        write_generated(auto)
        print("Generated and saved to generated.env:")
        for k in auto:
            print(f"  {k}")
        print()

    # Step 3: Write merged .env.docker (single-file env for docker compose)
    write_merged_docker_env()

    # Step 4: Final validation — everything required must now be set.
    required = [
        # TAILNET_NAME, not TAILNET_HOST_IP. The host IP is now optional — it
        # only decorates bootstrap.py's summary output. TAILNET_NAME is load-
        # bearing: it goes into SAB's host_whitelist, and without it SAB 403s
        # every tailnet request while working fine on loopback.
        "TZ", "TAILNET_NAME",
        "PLEX_LAN_IP", "PLEX_LAN_SUBNET",
        "VPN_PRIVATE_KEY", "VPN_ADDRESS", "VPN_CITY",
        "SABNZBD_API_KEY", "RADARR_API_KEY", "SONARR_API_KEY",
        "LIDARR_API_KEY", "PROWLARR_API_KEY",
        "USENET_HOST", "USENET_USER", "USENET_PASS",
        "NZBGEEK_API_KEY", "NZBPLANET_API_KEY",
        # Generated above, but required here rather than guarded in compose
        # with `${VAR:?}`. That syntax is interpolated for the whole project on
        # every invocation, so it turns `docker compose ps` and
        # `docker compose restart sabnzbd` into hard errors on any box whose
        # .env predates Nextcloud — 35 documented commands omit --env-file.
        # An empty NEXTCLOUD_REDIS_PASSWORD would otherwise stand up an
        # unauthenticated Redis, so it does need catching; this is the layer
        # where the error can name its own fix.
        "NEXTCLOUD_DB_PASSWORD", "NEXTCLOUD_REDIS_PASSWORD",
        "NEXTCLOUD_ADMIN_PASSWORD",
    ]
    missing = [k for k in required if not env.get(k, "").strip()]
    if missing:
        print("ERROR: These required values are still not set:")
        for k in missing:
            print(f"  {k}")
        sys.exit(1)

    # The Nextcloud plane binds /mnt/cache/appdata/... directly to bypass the
    # shfs FUSE layer, which is only safe while every appdata file lives on the
    # cache pool. Checked HERE, before the first file is written, rather than
    # inside ensure_nextcloud_appdata() — an abort mid-write would leave
    # bazarr's and tautulli's single-file bind mounts uncreated, and Docker
    # turns a missing bind-mount file into an empty directory.
    if _appdata_is_cache_only() is False:
        print("ERROR: the appdata share is not shareUseCache=only.")
        print()
        print("  Nextcloud's appdata is bind-mounted from /mnt/cache/appdata/... so it")
        print("  bypasses shfs. That is the same set of files as /mnt/user/appdata/...")
        print("  ONLY while the share is cache-only. With a secondary tier, files can")
        print("  also live on the array, the two paths diverge, and the speedup becomes")
        print("  data corruption.")
        print()
        print("  Fix: Shares -> appdata -> Secondary storage: none. See docs/decisions.md.")
        sys.exit(1)

    # Step 5: Write app configs.
    print("\nWriting config files...")
    write_sabnzbd(env)
    write_arr_config("radarr",   7878, env["RADARR_API_KEY"])
    write_arr_config("sonarr",   8989, env["SONARR_API_KEY"])
    write_arr_config("lidarr",   8686, env["LIDARR_API_KEY"])
    write_arr_config("prowlarr", 9696, env["PROWLARR_API_KEY"])
    ensure_seerr_appdata()
    ensure_profilarr_appdata()
    ensure_ollama_appdata()
    ensure_actual_appdata()
    ensure_chess_coach_appdata()
    ensure_nextcloud_appdata()
    write_bazarr(env)
    write_tautulli(env)

    # Step 6: Create data directories.
    print("\nCreating data directories...")
    create_data_dirs()

    if _PENDING_NEW_FILES:
        print("\n" + "-" * 60)
        print("Existing configs preserved; new templates written alongside:")
        for p in _PENDING_NEW_FILES:
            print(f"  diff {p} {p}.new")
        print("Reconcile (or delete the .new files) before starting the stack.")
        print("Re-run with --force-overwrite to replace existing files instead.")
        print("-" * 60)

    nc_user = env.get("NEXTCLOUD_ADMIN_USER", "admin")
    print(f"""
Done.

Next steps:
  1. Start the stack:
       docker compose --env-file .env.docker up -d
  2. Wait ~60s for containers to initialise.
  3. python3 scripts/bootstrap.py
  4. python3 scripts/sync-tailscale-services.py

Nextcloud installs itself on first start — there is no wizard. Log in as
'{nc_user}' with the generated password:
       grep ^NEXTCLOUD_ADMIN_PASSWORD= generated.env
""")

if __name__ == "__main__":
    main()
